- .github/workflows/pr.yaml
- Dockerfile
- config/rbac/role.yaml
- controllers/integration_controller.go
- controllers/suite_test.go
> Add pull request workflow

- Makefile
This commit adds the needed changes to being able to build and push an image with the operator.
Signed-off-by: David Moreno García <damoreno@redhat.com>
> feat: add variables to push image

- config/rbac/application_role_binding.yaml
- config/rbac/application_viewer_role.yaml
- config/rbac/applicationsnapshot_editor_role.yaml
- config/rbac/applicationsnapshot_role_binding.yaml
- config/rbac/applicationsnapshot_viewer_role.yaml
- config/rbac/component_editor_role.yaml
- config/rbac/component_role_binding.yaml
- config/rbac/component_viewer_role.yaml
- config/rbac/kustomization.yaml
- config/rbac/release_editor_role.yaml
- config/rbac/release_role_binding.yaml
- config/rbac/release_viewer_role.yaml
- config/rbac/releaselink_role_binding.yaml
- config/rbac/releaselink_viewer_role.yaml
- config/rbac/tekton_editor_role.yaml
- config/rbac/tekton_role_binding.yaml
Add the required RBAC definitions for all Custom Resource which the Integration controller interacts with.
> feat[HACBS-514]: Add RBAC definitions for managed CRs

- controllers/integration/integration_adapter.go
This commit adds functionality to the integration_adapter to only retrieve the ReleaseLinks
for an application if the ReleaseLink does not have the release.appstudio.openshift.io/auto-release
label set to false. A missing label is considered the same as it being there and set to true.
Signed-off-by: Johnny Bieren <jbieren@redhat.com>
> feat(HACBS-682): only create release if releaselink set to auto-release

- config/rbac/applicationsnapshotenvironmentbinding_editor_role.yaml
- config/rbac/applicationsnapshotenvironmentbinding_role_binding.yaml
- config/rbac/environment_editor_role.yaml
- config/rbac/environment_role_binding.yaml
- config/rbac/kustomization.yaml
> feat[HACBS-801]: Add RBAC definitions for gitOps CRs

- controllers/integration/integration_adapter.go
- controllers/integration/integration_controller.go
- tekton/predicates.go
- tekton/utils.go
* Add EnsureApplicationSnapshotPassedAllTests
* Add functions to find all integration tests for a given snapshot
* Adjust the controller to trigger off both build and integration pipelines
> feat(HACBS-878): Add decision logic checking Integration pipelines outcome

- controllers/integration/integration_adapter.go
Currently the [findExistingApplicationSnapshotEnvironmentBinding](https://github.com/redhat-appstudio/integration-service/blob/main/controllers/integration/integration_adapter.go#L418) function uses mutliple client.MatchingFields calls in order to find bindings that reference the specified environment as well as the application.
Unfortunately, due to the limitation of the FieldSelector filtering when used with cache-based implementations, this approach does not work correctly, and only the `spec.environment` is taken into account. This change does the following:
* findExistingApplicationSnapshotEnvironmentBinding refactored to use a single MatchingFields
* Use a for loop to filter based on application
* Fix related warnings raised by the IDE
> fix(HACBS-966): Loop over found bindings to filter based on application

- config/rbac/integrationtestscenario_role_binding.yaml
- config/rbac/kustomization.yaml
> fix(HACBS-809): Add the missing IntegrationTestScenario role binding

- .github/workflows/pr.yaml
- go.mod
- tekton/predicates_test.go
- tekton/tekton_suite_test.go
> feat[HACBS-806]:Add unit test for tekton functions

- config/kcp-rbac/application_role_binding.yaml
- config/kcp-rbac/application_viewer_role.yaml
- config/kcp-rbac/applicationsnapshot_editor_role.yaml
- config/kcp-rbac/applicationsnapshot_role_binding.yaml
- config/kcp-rbac/applicationsnapshot_viewer_role.yaml
- config/kcp-rbac/applicationsnapshotenvironmentbinding_editor_role.yaml
- config/kcp-rbac/applicationsnapshotenvironmentbinding_role_binding.yaml
- config/kcp-rbac/component_editor_role.yaml
- config/kcp-rbac/component_role_binding.yaml
- config/kcp-rbac/component_viewer_role.yaml
- config/kcp-rbac/environment_editor_role.yaml
- config/kcp-rbac/environment_role_binding.yaml
- config/kcp-rbac/integrationtestscenario_editor_role.yaml
- config/kcp-rbac/integrationtestscenario_role_binding.yaml
- config/kcp-rbac/integrationtestscenario_viewer_role.yaml
- config/kcp-rbac/kustomization.yaml
- config/kcp-rbac/leader_election_role.yaml
- config/kcp-rbac/leader_election_role_binding.yaml
- config/kcp-rbac/release_editor_role.yaml
- config/kcp-rbac/release_role_binding.yaml
- config/kcp-rbac/release_viewer_role.yaml
- config/kcp-rbac/releaseplan_role_binding.yaml
- config/kcp-rbac/releaseplan_viewer_role.yaml
- config/kcp-rbac/role.yaml
- config/kcp-rbac/role_binding.yaml
- config/kcp-rbac/service_account.yaml
- config/kcp-rbac/tekton_editor_role.yaml
- config/kcp-rbac/tekton_role_binding.yaml
- config/kcp/kustomization.yaml
- go.mod
> Add overlay for kcp

- .github/workflows/gosec.yaml
- go.mod
> feat(HACBS-1051): use gosec in CI workflow

- .github/workflows/codecov.yml
- .github/workflows/pr.yaml
- codecov.yml
Jira : [HACBS-1050](https://issues.redhat.com/browse/HACBS-1050)
> feat(HACBS-1050): Add codecov to integration-service

- controllers/pipeline/pipeline_adapter.go
- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_controller.go
Update the container image in the global candidate list to newly build image
> feat(HACBS-1011):Update the container image in the global list to newly build image

- .github/gitlint/description_conventional_commits.py
- .github/workflows/pr.yaml
- .gitlint
> feat(HACBS-1073): add gitlint support and description fix

- controllers/pipeline/pipeline_adapter.go
- controllers/pipeline/pipeline_controller.go
- gitops/gitops_suite_test.go
- gitops/snapshot.go
- gitops/snapshot_test.go
- tekton/utils.go
* Add createCompositeSnapshotsIfConflictExists functionality
* Modify snapshot creation functions, expand labels
* Mark snapshot as failed if superseded by composite snapshot
> feat(HACBS-1010): Create and manage composite snapshots

- config/kcp-rbac/role.yaml
- config/rbac/role.yaml
- controllers/pipeline/pipeline_controller.go
- controllers/snapshot/snapshot_controller.go
> fix(HACBS-1084): add application finalizer permissions

- README.md
* Add section for running, building and testing the operator
> docs(HACBS-1235): expand Readme to include running and testing info

- release/release_suite_test.go
- release/releaseplan_test.go
> feat(HACBS-1217): add unit testing for release functions

- controllers/pipeline/pipeline_adapter_test.go
- controllers/pipeline/pipeline_controller_test.go
- controllers/pipeline/pipeline_suite_test.go
Signed-off-by: srivickynesh <sselvan@redhat.com>
> feat(hacbs-1112): add unit testing for pipeline controller & adapter

- config/default/manager_auth_proxy_patch.yaml
- config/default/manager_config_patch.yaml
- config/kcp-rbac/application_role_binding.yaml
- config/kcp-rbac/applicationsnapshot_role_binding.yaml
- config/kcp-rbac/applicationsnapshotenvironmentbinding_role_binding.yaml
- config/kcp-rbac/component_role_binding.yaml
- config/kcp-rbac/environment_role_binding.yaml
- config/kcp-rbac/integrationtestscenario_role_binding.yaml
- config/kcp-rbac/leader_election_role_binding.yaml
- config/kcp-rbac/release_role_binding.yaml
- config/kcp-rbac/releaseplan_role_binding.yaml
- config/kcp-rbac/role.yaml
- config/kcp-rbac/role_binding.yaml
- config/kcp-rbac/service_account.yaml
- config/kcp-rbac/tekton_role_binding.yaml
- config/kcp/kustomization.yaml
- config/manager/manager.yaml
- config/rbac/role.yaml
- controllers/pipeline/pipeline_controller.go
- controllers/snapshot/snapshot_controller.go
Signed-off-by: Hongwei Liu  hongliu@redhat.com
> feat(HACBS-1150) fix apiexport for infra-deployments

- controllers/snapshot/snapshot_adapter_test.go
- controllers/snapshot/snapshot_controller.go
> fix(HACBS-1256): add fix for unit test errors during execution

- gitops/gitops_suite_test.go
- gitops/gitops_test.go
> feat(HACBS-1285): add unit testing for gitops binding function

- helpers/helpers_suite_test.go
- helpers/integration_test.go
> feat(HACBS-1284): add unit testing for integration functions

- config/kcp-rbac/applicationsnapshot_editor_role.yaml
- config/kcp-rbac/role.yaml
- config/kcp-rbac/tekton_editor_role.yaml
- config/rbac/applicationsnapshot_editor_role.yaml
- config/rbac/role.yaml
- config/rbac/tekton_editor_role.yaml
- controllers/pipeline/pipeline_controller.go
- controllers/snapshot/snapshot_controller.go
* Add patch/update applicationSnapshots/status RBACs
* Change the apiGroup for pipelineRun RBACs to tekton.dev
* Fix the case-sensitive resource names in controller kubebuilder directives
> fix(HACBS-1341): add patch/update for ApplicationSnapshot status

- config/kcp/apiexport_integration.yaml
- config/kcp/apiresourceschema_integration.yaml
Update apiresourceschema after EnvironmentConfiguration is added in IntegrationTestScenario
> feat(HACBS-1223): update apiresourceschema after EnvironmentConfiguration is added

- controllers/snapshot/snapshot_adapter.go
> fix(HACBS-1256): add fix to make test error

- api/v1alpha1/integrationtestscenario_suite_test.go
- api/v1alpha1/integrationtestscenario_types_test.go
- git/github/github_suite_test.go
- gitops/gitops_suite_test.go
- release/release_suite_test.go
- tekton/tekton_suite_test.go
> feat(HACBS-1312): add unit testing for integration API

- controllers/snapshot/snapshot_adapter.go
* Added logging to help debugging in staging
Replaces #32 because of refactoring changes
> feat: log the count of scenarios found

- controllers/pipeline/pipeline_adapter.go
- controllers/pipeline/pipeline_adapter_test.go
- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
- gitops/snapshot.go
- helpers/integration_test.go
- helpers/metadata.go
- helpers/metadata_test.go
- status/reporters_test.go
- status/status_test.go
Signed-off-by: Alex Misstear <amisstea@redhat.com>
> fix(HACBS-1385): change prefix for propagated PaC labels & annotations

- controllers/pipeline/pipeline_adapter.go
- controllers/pipeline/pipeline_adapter_test.go
- helpers/integration.go
- helpers/integration_test.go
- status/format.go
- status/format_test.go
- status/reporters.go
- status/reporters_test.go
Signed-off-by: Alex Misstear <amisstea@redhat.com>
> feat(HACBS-1387): improve GitHub status presentation

- config/rbac/role.yaml
- controllers/pipeline/pipeline_controller.go
These were accidentally omitted from prior commits.
Signed-off-by: Alex Misstear <amisstea@redhat.com>
> fix(HACBS-1439): fix permissions for Secrets and Repositories

- controllers/pipeline/pipeline_adapter.go
- controllers/pipeline/pipeline_adapter_test.go
* Add the skip condition and log to EnsureSnapshotExists
* Add more coverage to pipeline_adapter unit tests
> fix(HACBS-1434): skip snapshot creation if component is unknown

- controllers/pipeline/pipeline_adapter.go
- controllers/pipeline/pipeline_adapter_test.go
- controllers/pipeline/pipeline_controller.go
- controllers/pipeline/pipeline_controller_test.go
- controllers/snapshot/snapshot_adapter_test.go
- helpers/integration.go
- helpers/integration_test.go
- tekton/integration_pipeline.go
- tekton/integration_pipeline_test.go
Signed-off-by: @sonam1412 somahesh@redhat.com
This is to remove the test prefix from appstudio resource labels
> feat(HACBS-1331): remove the test prefix from appstudio resource labels

- controllers/pipeline/pipeline_adapter.go
- controllers/pipeline/pipeline_adapter_test.go
- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
- gitops/snapshot.go
> feat(HACBS-1533): allow releasing & deploying manually created Snapshots

- gitops/snapshot.go
- status/reporters_test.go
* Change the snapshot component label to refer to matching tekton label
* Minor refactors of Go doc comments for related labels
> fix(HACBS-1576): fix SnapshotComponentLabel reference

- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_controller.go
- gitops/snapshot_predicate.go
- gitops/snapshot_predicate_test.go
> feat(HACBS-1500): add filter for delete event for snapshot controller

- helpers/integration_test.go
Additional test that includes data intended to mimic a broken json file.
Signed-off-by: Josh Everett <jeverett@redhat.com>
> feat(HACBS-1253): enhance malformed json testing

- .github/dependabot.yml
GH actions will be updated automatically to the latest releases
> chore(HACBS-1634): configure dependabot to update GH actions

- controllers/pipeline/pipeline_adapter.go
- controllers/pipeline/pipeline_adapter_test.go
This was generating nonsense JSON, fixing log format
> fix(HACBS-1802): loggin format for skipping snapshot

- controllers/pipeline/pipeline_controller.go
...within the `getApplicationFromPipelineRun()` function
> Replace the occurrence of "componentName" with "applicationName"

- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
This PR updates the Global Candidate List with the commit sha for the built Component.
> feat(STONEINTG-354): update lastBuiltCommit with Revision field

- controllers/pipeline/pipeline_adapter.go
- controllers/pipeline/pipeline_adapter_test.go
The acceptance criteria stated "Updates for relevant unit/controller tests".  I believe I covered all relevant tests.  Please let me know if there are other places where I should be adding additional checks.
> feat(STONEINTG-371): Don't add a component to Snapshots if it doesn't have a container image defined

- go.mod
- go.sum
- helpers/integration.go
- status/format_test.go
Add a schema validation for test results using [jsonschema](https://github.com/santhosh-tekuri/jsonschema).
> feat(STONEINTG-202): Create a JSON schema for the standardized test output

- README.md
- controllers/binding/snapshotenvironmentbinding_adapter.go
- controllers/binding/snapshotenvironmentbinding_adapter_test.go
- controllers/pipeline/pipeline_adapter.go
- controllers/pipeline/pipeline_adapter_test.go
- controllers/pipeline/pipeline_controller_test.go
- controllers/scenario/scenario_adapter.go
- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
- gitops/gitops_test.go
- gitops/snapshot.go
- gitops/snapshot_predicate_test.go
- gitops/snapshot_test.go
- helpers/integration.go
- helpers/integration_test.go
- metrics/integration_test.go
- status/format.go
- status/format_test.go
- status/reporters_test.go
- status/status.go
Includes renaming of test output from HACBS_TEST_OUTPUT to TEST_OUTPUT.
> feat(STONEINTG-161): remove HACBS keyword from integration-service

- config/rbac/role.yaml
- controllers/binding/snapshotenvironmentbinding_controller.go
- controllers/pipeline/pipeline_controller.go
- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_controller.go
- gitops/environment.go
* Change kubebuilder directives to use lowercase for CRs
* Update the role.yaml accordingly
* If environment doesn't get created, delete DTC
* Check if ITS environment config is defined
> fix(STONEINTG-416): account for edge cases with namespace provisioning

- config/prometheus/kustomization.yaml
- config/prometheus/monitor.yaml
- config/prometheus/secret.yaml
- config/rbac/kustomization.yaml
- config/rbac/prometheus_role_binding.yaml
- config/rbac/prometheus_service_account.yaml
- config/rbac/prometheus_viewer_role.yaml
Prometheus has changed to use the service ServiceMonitors. Updating config to provide secret correctly.
> fix(STONEINTG-185): update ServiceMonitor

- controllers/binding/snapshotenvironmentbinding_adapter.go
- controllers/binding/snapshotenvironmentbinding_adapter_test.go
- controllers/binding/snapshotenvironmentbinding_controller.go
- controllers/pipeline/pipeline_adapter.go
- controllers/pipeline/pipeline_adapter_test.go
- controllers/pipeline/pipeline_controller.go
- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
- controllers/snapshot/snapshot_controller.go
- gitops/binding.go
- gitops/environment.go
- gitops/environment_test.go
- gitops/gitops_test.go
- gitops/snapshot.go
- gitops/snapshot_test.go
- helpers/integration.go
- helpers/integration_test.go
- loader/integration.go
- loader/integration_test.go
- loader/loader.go
- loader/loader_mock.go
- loader/loader_mock_test.go
- loader/loader_suite_test.go
- loader/loader_test.go
* Move adapter unit tests to use mock loaders
* Move some function to loader package to make the import smooth
> feat(STONEINTG-172): move adapter unit tests to use mock loaders

- config/grafana/dashboards/integration-service-dashboard.json
Add all SLIs to grafana.
Includes also basic SLOs.
> feat(STONEINTG-185): add all SLIs to grafana

- config/grafana/dashboards/integration-service-dashboard.json
Update grafana dashboard with:
- Remove unwanted SLO
- Fix time ranges
- Add measurements of SLO violations
> feat(STONEINTG-185): update SLOs in grafana

- .snyk
- .tekton/push.yaml
When new reference is pushed, automatically update grafana dahsboard in infra repo
> chore(tekton): automatically update grafana dashboard

- config/grafana/dashboards/integration-service-dashboard.json
Heatmaps werent plotted correctly and needed a few changes
> fix(STONEINTG-185): fix grafana heatmaps

- docs/snapshot-controller.md
Addresses [STONEINTG-473](https://issues.redhat.com/browse/STONEINTG-473)
* Click on "Files changed"
* Click the three dots on the top-right of the file
* Click on "View file"
* Go to [mermaid.live](https://mermaid.live/)
* Paste this diagram's code
* Change the code the way you want, and see the changes instantly there.
* You can refer to [this Mermaid cheatsheet](https://jojozhuang.github.io/tutorial/mermaid-cheat-sheet/) to propose any changes.
* Content of the diagram
* and anything else
> docs(STONEINTG-473): add diagram of Snapshot Controller

- controllers/binding/snapshotenvironmentbinding_suite_test.go
- controllers/pipeline/pipeline_adapter_test.go
- controllers/pipeline/pipeline_controller_test.go
- controllers/pipeline/pipeline_suite_test.go
- controllers/scenario/scenario_suite_test.go
- controllers/snapshot/snapshot_adapter_test.go
- controllers/snapshot/snapshot_controller_test.go
- controllers/snapshot/snapshot_suite_test.go
> feat(STONEINTG-459): remove cache from controller unittest

- docs/binding-controller.md
Add a diagram to documentation that maps the flow of the SnapshotEnvironmentBinding controller
> chore(STONEINTG-476): SnapshotEnvironmentBinding Controller diagram

- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
* If environment is not ephemeral, set application as owner
* The SEBs for ephemeral Envs are expected to be cleaned up along with the Environment
* All other SEBs are meant to persist and be deleted with the Application
> fix(RHTAPBUGS-498): set application as owner of SEB

- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
- loader/loader.go
- loader/loader_mock.go
- loader/loader_suite_test.go
- loader/loader_test.go
- release/releaseplan.go
- release/releaseplan_test.go
amended to one commit with extended commit message
> Stoneintg 477

- controllers/binding/snapshotenvironmentbinding_controller.go
Update snapshot environment binding controller's adapter interface to reflect new ensure function.
> fix(STONEINTG-433): update SEB AdapterInterface

- docs/binding-controller.md
Update mermaid flowchart for snapshotEnvironmentBinding controller to include EnsureEphemeralEnvironmentsCleadUp function.
> docs: update SEB controller diagram with deployment failed predicate

- controllers/buildpipeline/buildpipeline_controller_test.go
- controllers/integrationpipeline/integrationpipeline_adapter.go
- controllers/integrationpipeline/integrationpipeline_controller.go
- controllers/integrationpipeline/integrationpipeline_controller_test.go
- helpers/integration_test.go
In STONEINTG-493, we split PLR controller to build PLR controller and integration PLR controller, this PR is to update some text/message which are not updated in https://github.com/redhat-appstudio/integration-service/pull/257 
> fix: update a few text/message in build/integration PLR

- docs/README.md
- docs/build_pipeline_controller.md
- docs/integration_pipeline_controller.md
- [x ] Commit messages are descriptive enough ([hints](https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/))
> chore: add diagrams for integration and build pipeline controller

- .github/dependabot.yml
Add Ryan to reviewers of dependabot changes
> chore(dependabot): add Ryan to reviewers

- controllers/snapshot/snapshot_adapter.go
> fix(STONEINTG-574) fix log message about number of integration tests

- controllers/binding/snapshotenvironmentbinding_adapter_test.go
Changed  'Requeues the environment cleanup if the binding is younger
than the threshold' test case to totally use mocked context CRs.
> fix(STONEINTG-595): resolve race condition about DeploymentTargetClaim

- loader/loader_test.go
Refactored code, to create release plans only for tests cases they need it, with proper creation and deletion using `When` statement, instead of doing creation and removal of objects within test cases.
Now it also checks if objects were removed before moving to next testcase to avoid race conditions.
Also, suprisingly there was a Release Plan created in beforeAll with the only purpose being removed in test case testing releae plans. I identified this as missing coverage and added additional test case "when release plan has auto-release label set"
> fix(STONEINTG-593): race condition in tests with releasePlans

- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
* refactor the function to create integrationPipelinerun
> feat(STONEINTG-538): refactor EnsureAllIntegrationTestPipelinesExist()

- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
Instead of copy pasting checking for non-empty environemnt definition in scenario spec, abstract it into function with clear semantincs, that make code much easier to read.
Also easy unittest for free.
> refactor(STONEINTG-539): abstract detection of ephemeral env

- controllers/scenario/scenario_adapter.go
- controllers/scenario/scenario_adapter_test.go
* If the ITS was already migrated from v1alpha1, it might not have its status.conditions set at all. This change adds it as part of the scenario controller reconciliation
> fix(STONEINTG-583): add status.conditions to existing ITS

- controllers/binding/snapshotenvironmentbinding_adapter.go
- metrics/integration.go
> feat(STONEINTG-535): SLI successful/failed ephemeral environment deloyments

- config/grafana/dashboards/integration-service-dashboard.json
Panel one Latency of release creation
Panel two violations of the 90% in 10 seconds slo
> feat(STONEINTG-533): add 2 panels for SLO #3

- config/grafana/dashboards/integration-service-dashboard.json
Also change SLO numer from 3 to 5
> fix(STONEINTG-533: Fix parsing error in SLO 5 expression

- controllers/binding/snapshotenvironmentbinding_adapter.go
- controllers/integrationpipeline/integrationpipeline_adapter.go
- controllers/integrationpipeline/integrationpipeline_adapter_test.go
- controllers/snapshot/snapshot_adapter.go
- controllers/statusreport/statusreport_adapter.go
- controllers/statusreport/statusreport_controller.go
- docs/integration_pipeline_controller.md
- docs/statusreport-controller.md
- helpers/finalizers.go
- helpers/integration.go
- loader/integration.go
- pkg/integrationteststatus/integration_test_status.go
- pkg/integrationteststatus/integration_test_status_test.go
- pkg/integrationteststatus/integrationteststatus_enumer.go
- status/reporters.go
- tekton/integration_pipeline.go
- tekton/integration_pipeline_test.go
- tekton/predicates.go
- tekton/predicates_test.go
- tekton/utils.go
> feat(STONEINTG-599): add finalizers to Integration PLR

- config/grafana/dashboards/integration-service-dashboard.json
Adding panel for showing metric of SEB total deployments, both failed and successfull.
> feat(STONE-535): Adding panel for SLI SEB Total

- controllers/snapshot/snapshot_controller.go
- controllers/snapshot/snapshot_controller_test.go
* stop snapshot reconciliation if its application doesn't exist
* mark snapshot as invalid if its application doesn't exist
> fix(STONEINTG-643): don't process snapshot with nonexisting app

- controllers/buildpipeline/buildpipeline_controller.go
- controllers/buildpipeline/buildpipeline_controller_test.go
* Retry fetching component for build pipelineRun
* Remove finalizer if component is not found after retrying
> fix(STONEINTG-649): remove finalizer when component is missing

- controllers/buildpipeline/buildpipeline_adapter.go
- controllers/buildpipeline/buildpipeline_adapter_test.go
- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
- gitops/snapshot.go
> feat(STONEINTG-671): add application/component label to new releases

- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
This patch adds a check for verifying the environemnt used for the creation of an ITS is a valid kubernetes object. When an invalid environment is found to be refrenced by the snapshot controller during the generation of an ITS, the snapshot controller will stop reconcilliation instead of requeuing with an error.
> fix(STONEINTG-580): handle invalid environments

- controllers/binding/snapshotenvironmentbinding_adapter_test.go
- controllers/buildpipeline/buildpipeline_adapter_test.go
- controllers/buildpipeline/buildpipeline_controller.go
- controllers/component/component_adapter_test.go
- controllers/snapshot/snapshot_adapter_test.go
- git/github/github_test.go
- gitops/binding_test.go
- gitops/environment_test.go
- gitops/snapshot_integration_tests_status_test.go
- gitops/snapshot_test.go
- helpers/integration_test.go
- loader/loader_test.go
- pkg/integrationteststatus/integration_test_status_test.go
- status/status_test.go
- tekton/integration_pipeline_test.go
> STONEINTG-661: Fix golangci reported issues

- cmd/snapshotgc/snapshotgc.go
- cmd/snapshotgc/snapshotgc_test.go
Discard newest snapshots from list of delete candidates
> chore(RHTAPWATCH-731): keep newest snapshots

- controllers/buildpipeline/buildpipeline_adapter.go
- controllers/buildpipeline/buildpipeline_adapter_test.go
When we cannot create a snapshot, we shouldn't block build PLR with finalizers, but rather let users to restart build.
> fix(RHTAPBUGS-1119): don't block build PLR removal

- controllers/buildpipeline/buildpipeline_adapter.go
Fix log entry to correctly log pipeline name
> fix(buildPLR): log entry was not logging correctly

- cmd/snapshotgc/snapshotgc.go
- cmd/snapshotgc/snapshotgc_test.go
- go.mod
- go.sum
Snapshot garbage collection main loop and main function with command line arguments.
> chore(RHTAPWATCH-758): add snapshot garbage collection main loop

- controllers/integrationpipeline/integrationpipeline_adapter.go
- helpers/integration.go
- tekton/integration_pipeline_test.go
> fix: the misleading log message

- loader/loader_test.go
* The current version of unittests is flaky when run in GitHub actions because of latency when creating the TaskRun
* See [this failed run](https://github.com/redhat-appstudio/integration-service/actions/runs/7957738200/job/21721416963) for example
> fix: simplify unittest for GetAllTaskRunsWithMatchingPipelineLabel

- status/format.go
- status/format_test.go
- status/status.go
- status/status_test.go
> feat(STONE-812): url mapping to console url

- status/reporter_gitlab.go
- status/reporter_gitlab_test.go
Check if there is existing commitStatus and compare the status before calling r.client.Commits.SetCommitStatus. 
If the old and new status are both "Running", don't update commitStatus state
> fix(STONEINTG-835): don't update running gitlab commitStatus

- README.md
> docs: rename Appstudio to Konflux in readme

- .tekton/integration-service-pull-request.yaml
- .tekton/integration-service-push.yaml
> fix: clair-scan tekton task reference

- status/reporter_gitlab.go
- status/reporter_gitlab_test.go
This change adds a link to the Konflux console in the pipeline view on gitlab _if_ the cluster has a console (determined by the value of CONSOLE_URL in the integration service manager pod.
A sample pipeline can be viewed [here](https://gitlab.cee.redhat.com/rycole/webhook-test/-/pipelines/8040272). Note: I hardcoded the URL for the pod since there was no console in the cluster being used to test the change.
> feat(stoneintg-842): Link plr console URL into gitlab commit status

- internal/controller/statusreport/statusreport_adapter.go
There was recently an issue in which the integration service was not creating releases for a customer whose snapshot passed all required tests but failed one optional test.  This additional logging will help us to verify whether the integration service is grouping mandatory and optional tests together in the status report controller
> chore: add additional logging to status report controller

- config/rbac/role.yaml
- internal/controller/snapshot/snapshot_controller.go
Reverts konflux-ci/integration-service#735
This workaround shouldn't be needed anymore
> Revert "fix(KFLUXBUGS-1299): add delete permissions for components"

- internal/controller/buildpipeline/buildpipeline_adapter.go
Cognitive complexity was reduced from 31 to <15
> feat(STONEINTG-825): reducing cognitive complexity

- status/reporter.go
- status/reporter_github.go
> chore: fix names and logs more data for clarity

- status/reporter_github.go
- status/reporter_github_test.go
Before this commit:
* When we were updating a pre-existing checkrun,
the correct status wouldn't get reflected on the
GH until the test is finished.
* This is expected behaviour as per GH: An already
"completed" checkrun should NOT be updated to
a non-completed status.
* Instead, we should create another checkrun with
the same external ID and that would reset the
already completed the checkrun correctly.
* Source: "https://github.com/isaacs/github/issues/1530#issuecomment-599958904"
After this commit:
* The users can see the correct status AND total
duration of Checkrun, while retriggering their tests.
> fix(STONEINTG-939): update checkruns correctly

- cmd/snapshotgc/snapshotgc.go
- cmd/snapshotgc/snapshotgc_test.go
* cleanup the unused/unreleased override snapshot in snapshot GC
> feat(STONEINTG-973): cleanup the unused/unreleased override snapshot

- internal/controller/snapshot/snapshot_adapter.go
- internal/controller/snapshot/snapshot_adapter_test.go
Before this commit:
* If there were 0 ReleasePlans available when a a Snapshot passed all of its required tests or there were 0 tests, the Snapshot's "AutoRelease" condition type's message field would contain the text "The Snapshot was auto-released".
* Which is misleading as the Snapshot couldn't be released due to 0 ReleasePlans available.
After this commit:
* We will check the count of ReleasePlans and if its 0 then we would still mark snapshot as AutoRelease but make sure to mention this in its message field.
* This would help users who are wondering why there are no release(s) even though the snapshot is marked as AutoReleased.
> feat(STONEINTG-967): consider 0 ReleasePlans in 'AutoReleased' field

- status/status.go
* This should prevent from PLR
* stuck on In-Progress state
> fix(STONEING-938): adding retryOnConflict block

- status/reporter_gitlab.go
Gitlab api will returns 400 error code when trying to update commit status with invalid one: 
- transition  from `running` to  `enqueue`
-  transition from `pending`  to  `enqueue`
for more details it can be tracked in [STONEINTG-1018](https://issues.redhat.com/browse/STONEINTG-1018)
> fix(Stoneintg 1018): handle invalid Gitlab api commit status update

- integration-tests/pipelines/konflux-e2e-tests.yaml
> feat: add test-name param to quality-dashboard task

- api/v1beta2/integrationtestscenario_webhook.go
- api/v1beta2/integrationtestscenario_webhook_test.go
According to the [Tekton Git Resolver](https://tekton.dev/docs/pipelines/git-resolver/#parameters)  we should not enable ITS creation if both parameters exists in git resolver , URL & Repo+Org 
[STONEINTG-957](https://issues.redhat.com/browse/STONEINTG-957)
> feat(STONEINTG-957): validate ITS if git resolver

- internal/controller/scenario/scenario_controller.go
* retry when getting application for ITS to avoid race condition when application and ITS are created at the same time
> fix(STONEINTG-1066): retry when finding application for ITS

- .dockerignore
- .tekton/integration-service-pull-request.yaml
- .tekton/integration-service-push.yaml
- Dockerfile
- integration-tests/pipelines/konflux-e2e-tests.yaml
> feat(KFLUXDP-107): Integrate Sealights tasks into integration service pipelines

- internal/controller/buildpipeline/buildpipeline_adapter.go
- internal/controller/buildpipeline/buildpipeline_adapter_test.go
* requeue initializing integration status if pr group info has not been added to build PLR
> fix(STONEINTG-1131): requeue initializing intg status when pr group info is not found in build PLR

- .github/CODEOWNERS
> chore: Offboard Dheeraj from Integration Service

- config/crd/kustomization.yaml
- config/default/kustomization.yaml
> fix(STONEINTG-1186): kustomization build failed on ArgoCD

- internal/controller/snapshot/snapshot_controller_test.go
- fix unittest "can add the Application as a
Controller OwnerReference on Snapshot"
- moved Expect statements inside eventually
to wait for controller to complete
- added clear comments explaining the flow of the test
> fix(stoneintg-1292): fix unittest OwnerReference on Snapshot

- internal/controller/buildpipeline/buildpipeline_adapter.go
- internal/controller/buildpipeline/buildpipeline_adapter_test.go
* When a build plr fails, make sure it is the latest build pipelinerun for component, otherwise don't notify the failure to other build PLRs and component snapshots
* When a new running pipelineRun is annotated with the group, annotate the snapshots and other build pipelineRuns about it  so we're aware that we're expecting the group Snapshot to be updated after it finishes
* This also resets the pr group creation annotation in case a previous build pipelineRun failed
> fix(KONFLUX-9147): don't notify group failure if not latest build

- status/reporter_gitlab.go
- status/reporter_gitlab_test.go
This commit aligns the integration service gitlab PR status update strategy with that of PaC.  Comment from PaC:
By default, Pipelines-as-Code attempts to update the commit status through the GitLab API. It first tries the source project (fork), then falls back to the target project (upstream repository). The source project update succeeds when the configured token has access to the source repository and GitLab creates pipeline entries for external CI systems like Pipelines-as-Code. The target project fallback may fail if there's no CI pipeline running for that commit in the target repository, since GitLab only creates pipeline entries for commits that actually trigger CI in that specific project. If either status update succeeds, no comment is posted on the Merge Request.
> fix(stoneintg-1352): fall back on target project updating PR status
