konflux-ci/integration-service

- .github/workflows/pr.yaml
- Makefile
- config/kcp/apiexport_integration.yaml
- config/kcp/apiresourceschema_integration.yaml
- config/kcp/kustomization.yaml
- hack/generate-kcp-api.sh
This commit adds the APIResourceSchema for the integration service. This
is needed for KCP integration. The generate-kcp-api.sh script is copied
from the has and spi repos.
> feat(HACBS-712) Generate apiresourceschema

- Dockerfile
The current image was causing problems while building the operator as buildah doesn't use Docker Hub by default.
Signed-off-by: David Moreno García <damoreno@redhat.com>
> fix(HACBS-1027): use a Red Hat provided image

- helpers/helpers_suite_test.go
- helpers/metadata_test.go
[HACBS-805](https://issues.redhat.com/browse/HACBS-805) Add unit testing for integration-service helper functions.
> feat(HACBS-805): Add unit testing for helper functions

- tekton/integration_pipeline.go
- tekton/integration_pipeline_test.go
- tekton/tekton_suite_test.go
Adding unit tests covering new functionality added in HACBS-463
Output after running `make test`
```
KUBEBUILDER_ASSETS="/home/jsztuka/.local/share/kubebuilder-envtest/k8s/1.23.5-linux-amd64" go test ./... -coverprofile cover.out
?       github.com/redhat-appstudio/integration-service [no test files]
?       github.com/redhat-appstudio/integration-service/api/v1alpha1    [no test files]
ok      github.com/redhat-appstudio/integration-service/controllers     5.292s  coverage: 0.0% of statements
?       github.com/redhat-appstudio/integration-service/controllers/pipeline    [no test files]
?       github.com/redhat-appstudio/integration-service/controllers/results     [no test files]
ok      github.com/redhat-appstudio/integration-service/controllers/snapshot    9.487s  coverage: 69.6% of …
```
> feat[HACBS-463]-adding unit tests

- controllers/pipeline/pipeline_adapter.go
- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
* Extract the ASEB handing functions from Ensure block
* Add `SetControllerReference` calls when creating new CRs
* Wrap snapshot adapter tests with additional `Eventually` calls
* The `SetControllerReference` causes delays in tests
* The added `Eventually` calls ensure that we wait for CRs to show up
Running the `SetControllerReference` function adds the application to the `ownerReferences` for a given CR, e.g.:
```
ownerReferences:
- apiVersion: appstudio.redhat.com/v1alpha1
blockOwnerDeletion: true
controller: true
kind: Application
name: application-sample
uid: 87b43fc8-e48b-4b92-8bd8-d61404f82c1f
```
> feat(HACBS-1084): set ownerRef on ApplicationSnapshots and ASEBs

- config/kcp-rbac/kustomization.yaml
The integration-service has overlapping cluster roles with the release service. This commit adds a namePrefix to the cluster roles in this repo so that they do not conflict with the release service.
> feat(HACBS-1150): add namePrefix to kcp-rbac

- .github/workflows/codecov.yml
This should resolve codecov run failures like https://github.com/redhat-appstudio/integration-service/actions/runs/3416438020/jobs/5686581511
> fix(HACBS-1383): use go v1.18 in the codecov GitHub action

- Dockerfile
> feat(HACBS-1215): use the Red Hat go 1.18 image in the Integration service

- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
- controllers/snapshot/snapshot_controller.go
- gitops/environment.go
- gitops/environment_test.go
- gitops/snapshot.go
- go.mod
Signed-off-by: jsztuka <jsztuka@redhat.com>
Adding a logic for creation of ephemeral environments.
Order of logic:
Integration service checks `integrationTestScenario` for presence of env attribute.
When the attribute exists - it check if the environment exist.
In case it does - create copy of this environment with updated envVars from IntegrationTestScenario.
Envs are created by this pattern: `IntegrationTestScenario x snapshot`
Corresponding labels are attached to newly created environment - snapshot, integrationTestScenario
For each snapshot the environmentbinding is created also.
Example targetNamespace that was created by process: `example-its-example-b81eabe8-6e53-425c-970c-0eb0baa0214b`
> feat(HACBS-1232): create ephemeral Env/Binding

- controllers/snapshot/snapshot_adapter.go
- gitops/snapshot.go
- gitops/snapshot_test.go
Set the snapshot integration status condition upon starting and finishing Integration testing
> feat(HACBS-1407): Set the snapshot upon starting and finishing Integration testing

- controllers/pipeline/pipeline_adapter.go
- controllers/snapshot/snapshot_adapter.go
- helpers/integration.go
- helpers/integration_test.go
The goal of this fix is for Integration service to correctly detect that an integration pipelineRun is already running when the snapshot controller is triggered before the existing pipelineRun finishes
* Add GetAllPipelineRunsForSnapshotAndScenario function
* Use the above function in EnsureAllIntegrationTestPipelinesExist
* Look for pipelineRuns in the snapshot's namespace
* Update unit tests accordingly
> fix(HACBS-1586): separate logic for getting existing pipelineRuns

- controllers/pipeline/pipeline_adapter.go
Follow-on fix for a edge case error that happens if the component can't be found (because of a label mismatch caused by HACBS-1576 or an issue with manual/e2e testing) when the pipeline controller runs the composite snapshot check.
* Check for component existence before running composite logic
* Use the HasLabelWithValue to check Snapshot type
> fix(HACBS-1576): fix composite snapshot checking

- config/rbac/role.yaml
- controllers/scenario/scenario_controller.go
Signed-off-by: Jiri Sztuka <jsztuka@redhat.com>
Changes are supposed to fix following:
```1.6759525873991888e+09
ERROR    controllers.integrationTestScenario    Failed to update Scenario    
{"IntegrationTestScenario": 
"sbudhwar-1-tenant/component-integration-test-one", "Scenario.Name:": 
"component-integration-test-one", "error": 
"integrationtestscenarios.appstudio.redhat.com 
\"component-integration-test-one\" is forbidden: User 
\"system:serviceaccount:integration-service:integration-service-controller-manager\"
cannot patch resource \"integrationtestscenarios/status\" in API group 
\"appstudio.redhat.com\" in the namespace \"sbudhwar-1-tenant\""}```
> fix(HACBS-1503): add rbac groups to SA

- Dockerfile
ubi-minimal:8.6 is deprecated and doesn't receive vulnerability fixes anymore. Bump to 8.7
Signed-off-by: Martin Basti <mbasti@redhat.com>
> fix(Dockerfile): bump ubi-minimal version to 8.7

- .github/dependabot.yml
This dependabot can detect dependencies version update and create pr for them automatically, more details can be found in https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
This is the first PR to use dependabot, we just make it detect the docker image version update.
[Here](https://github.com/hongweiliu17/dependabot-test/blob/main/.github/dependabot.yml) is the merged dependatbot in my personal repo and it generates [two PRs](https://github.com/hongweiliu17/dependabot-test/pulls) to update docker image in my repo.
> feat(HACBS-1536): add dependabot to detect dependencies update

- .gitlint
Splitting dependabot commit message into shored lines wouldn't bring any benefits in readability, let's ignore it
> chore(gitlint): ignore dependabot

- .github/dependabot.yml
* Use dependabot to detect go package update and create PR
Signed-off-by: Hongwei Liu  hongliu@redhat.com
> fix(HACBS-1636): update dependabot to include go packages

- controllers/pipeline/pipeline_adapter_test.go
- controllers/pipeline/pipeline_controller.go
- controllers/pipeline/pipeline_controller_test.go
- controllers/snapshot/snapshot_adapter_test.go
> fix(HACBS-1535): Improve test coverage

- controllers/snapshot/snapshot_adapter.go
- tekton/integration_pipeline.go
- tekton/integration_pipeline_test.go
This makes sure that the parameters provided via the `params` field of IntegrationTestScenarioSpec are passed to the derived PipelineRun.
> fix: pass scenario parameters to the pipeline

- .tekton/pull-request.yaml
- .tekton/push.yaml
Switching to new bundle since development of old one was stopped before attempt to migrate to kcp. New bundle is removing dependency on shared secret.
> chore: STONEBLD-777 - tekton-ci: update bundle

- controllers/pipeline/pipeline_adapter.go
- controllers/pipeline/pipeline_adapter_test.go
- go.mod
- go.sum
- helpers/integration.go
- helpers/integration_test.go
- tekton/utils.go
- tekton/utils_test.go
Fixing race condition where older pipeline could replace newer
deployment with image from older pipeline, if older pipeline was running
longer than latest one.
> Prevent out-of-order deployments

- .github/workflows/codeql.yml
This CodeQL workflow can detect security flaws in our code by running scans.
We can view the results and fix issues before merging the code changes.
Signed-off-by: Dheeraj Singh Jodha djodha@redhat.com
> feat(HACBS-1637): add CodeQL workflow to detect security flaws in code

- go.mod
- go.sum
We are having issues with deprecated dependency.
Newer version of application api doesn't use deprecated dependency of sigs.k8s.io/controller-runtime/pkg/envtest/printer
> chore(deps): bump redhat-appstudio/application-api version

- .github/workflows/pr.yaml
- Dockerfile
Fixes: [HACBS-1629](https://issues.redhat.com/browse/HACBS-1629)
Hadolint is a Dockerfile linter that helps you build best practice Docker images.
> feat(HACBS-1629): Dockerfile linter

- controllers/pipeline/pipeline_adapter.go
- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
- controllers/snapshot/snapshot_controller.go
- gitops/snapshot.go
- gitops/snapshot_predicate.go
- gitops/snapshot_predicate_test.go
- gitops/snapshot_test.go
Change the logic for updating the GCL (Global Candidate List).
* Move setting integration status to pipeline adapter
* Mark the Snapshot as invalid if superseded
* Add IsSnapshotValid and CanSnapshotBePromoted functions
* Check CanSnapshotBePromoted in snapshot adapter
* Add HasSnapshotTestingChangedToFinished function
* Use the function for snapshot update events
> fix(HACBS-1779): update the GCL promotion logic 

- config/manager/kustomization.yaml
- config/manager/network_policy.yaml
This is for security hardening, integration-service is not supposed to be communicating with the internet, only kube-api should be allowed.
Note: this also blocks DNS resolving
> feat(STONEINTG-291): Deny egress connections

- controllers/pipeline/pipeline_adapter.go
- controllers/pipeline/pipeline_adapter_test.go
- gitops/snapshot.go
This change makes easier to find which build pipeline created a snapshot.
> feat(STONEINTG-346): expose build pipeline in snapshot

- config/rbac/component_editor_role.yaml
- config/rbac/role.yaml
- controllers/snapshot/snapshot_controller.go
Previously merged PR: #141 deals with updating the `Status` field of the component, but currently our service doesn't have the required permissions to do this. So this PR adds those permissions and fixes the [failing e2e-test](https://github.com/redhat-appstudio/infra-deployments/pull/1638#issuecomment-1503315698).
> fix: set permissions to update Component.Status

- controllers/pipeline/pipeline_adapter_test.go
- controllers/scenario/scenario_adapter_test.go
- controllers/scenario/scenario_controller_test.go
- controllers/snapshot/snapshot_adapter_test.go
- gitops/gitops_test.go
- gitops/snapshot_test.go
- helpers/integration_test.go
- release/releaseplan_test.go
This is outlined more thoroughly in Jira, but basically using `Expect(a == b).To(BeTrue())` isn't idiomatic and hides important information in the case that tests fail.  This MR fixes statements like that throughout our unit tests.
> test(STONEINTG-385): update unit tests to be more clear about errors

- config/rbac/role.yaml
- controllers/pipeline/pipeline_adapter.go
- controllers/pipeline/pipeline_adapter_test.go
- controllers/pipeline/pipeline_controller.go
- controllers/pipeline/pipeline_controller_test.go
- go.mod
- go.sum
- helpers/integration.go
- helpers/integration_test.go
- status/format_test.go
- status/reporters.go
- status/reporters_test.go
- status/status.go
- status/status_suite_test.go
- status/status_test.go
- tekton/utils.go
- tekton/utils_test.go
* Upgrade tektoncd/pipeline to v0.45.0
* Stop supporting embedded TaskRun statuses in pipelineRuns
* Refactor GitHub reporter to utilize the new functions
* Refactor tekton utils to fetch PipelineRun results for output image URL and digest
* Update all unit tests to use the childReference TaskRuns
> feat(STONEINTG-180): migrate to pipelineRun TaskRun childReferences

- config/rbac/role.yaml
- controllers/binding/snapshotenvironmentbinding_adapter.go
- controllers/binding/snapshotenvironmentbinding_adapter_test.go
- controllers/binding/snapshotenvironmentbinding_controller.go
- controllers/binding/snapshotenvironmentbinding_controller_test.go
- controllers/binding/snapshotenvironmentbinding_suite_test.go
- controllers/controllers.go
- controllers/snapshot/cache.go
- controllers/snapshot/snapshot_controller.go
- gitops/binding.go
- gitops/environment.go
- gitops/environment_test.go
- gitops/predicates.go
- gitops/predicates_test.go
- tekton/integration_pipeline.go
- tekton/integration_pipeline_test.go
Copied most of code from https://github.com/redhat-appstudio/integration-service/pull/81 and add the code for the new Environments API
* Add binding controller for test pipeline deployments on ephemeral envs
* Add functions that can detect a SEB with a finished deployment
* Ensure creation of test pipelines with associated DT
* Add unit tests for the binding controller
* Add unit tests for updated code in other packages
> feat(STONEINTG-333): create a controller to trigger integration pipeline

- config/rbac/role.yaml
- controllers/pipeline/pipeline_adapter.go
- controllers/pipeline/pipeline_adapter_test.go
- controllers/pipeline/pipeline_controller.go
- controllers/pipeline/pipeline_suite_test.go
- helpers/integration.go
- tekton/predicates.go
- tekton/predicates_test.go
- tekton/utils.go
(This pr copies most of code in https://github.com/redhat-appstudio/integration-service/pull/81)
After the integration testing pipeline completes(succeed, skipped), we need to delete the CRs created for it.
* delete the ephemeral env
* delete deploymentTarget
* delete deploymentTargetClaim
* delete snapshotenvironmentbinding
This PR reference the code added in https://github.com/redhat-appstudio/integration-service/pull/154 and so should be rebased after merging https://github.com/redhat-appstudio/integration-service/pull/154.
> feat(STONEINTG-334): delete ephemeral Env CRs after int testing completes

- controllers/pipeline/pipeline_controller.go
- tekton/predicates.go
- tekton/predicates_test.go
- tekton/utils.go
PipelineRun are signed with tekton chains after they finish. We are
hitting race condition than sometimes we are creating release without
signed pipeline and cause error mentioned in subject.
Reconcile only build pipelines which have been signed
by tekton chains to avoid this issue.
Signed pipelineRuns are marked with annotation chains.tekton.dev/signed
> fix(STONEINTG-419): Release pipeline run fails on missing attestation

- controllers/pipeline/pipeline_adapter.go
We should refrains from using exclamation marks in text/logs/messages
> fix: don't use exclamation marks in text

- Dockerfile
Reverts redhat-appstudio/integration-service#172
> Revert "chore(Dockerfile): bump ubi8/go-toolset from 1.18.10-1 to 1.19.6-4"

- .github/workflows/pr.yaml
- Dockerfile
- controllers/scenario/scenario_controller_test.go
- go.mod
Go 1.18 is quite old and our dependecies already requires go 1.19 as min version. Moving to 1.19 will allow us to use latest versions of libraries.
> chore(STONEINTG-379): use go 1.19

- config/crd/kustomization.yaml
- config/crd/patches/cainjection_in_integrationtestscenarios.yaml
- config/crd/patches/webhook_in_integrationtestscenarios.yaml
- config/default/kustomization.yaml
- config/default/webhookcainjection_patch.yaml
- config/webhook/kustomization.yaml
- config/webhook/manifests.yaml
- config/webhook/service.yaml
Following changes inject CA bundle directly to the webhook so its not needed to be provided by third party operator.
> Drop cert manager dependency from webhook.

- controllers/pipeline/pipeline_adapter_test.go
- helpers/integration.go
- helpers/integration_test.go
- loader/integration.go
* get the lastest finished pipeline when trying to get latest pr
* create scenario in helpsers.integration_test.go and adjust unittest
* add Eventually to make sure the global component list is changed successfully before creating composite snapshot
> fix(STONEINTG-431): make snapshot as failed if pipline of one scenario fails

- controllers/pipeline/pipeline_adapter.go
- controllers/pipeline/pipeline_adapter_test.go
- controllers/pipeline/pipeline_controller.go
- helpers/metadata.go
- helpers/metadata_test.go
- loader/loader_test.go
- tekton/predicates.go
- tekton/predicates_test.go
- tekton/utils.go
* Build pipelineRuns are annotated with created Snapshots
* Expand build pipelineRun predicate to ignore annotated pipelineRuns
* Only require that build pipelineRun is signed by chains operator
* Require that the build pipelineRun is succeeded
> feat(STONEINTG-458): build pipelineRuns are annotated with Snapshots

- Makefile
- README.md
Our Makefile only supports docker.  Since podman is developed at Red Hat cri-o is the default OpenShift runtime, we should also make sure we support development using podman.  This is just a quick change to the Makefile and documentation to enable users to override the default docker container runtime via the 'CONT_ENGINE' environment variable.
Note: I grepped for references to `docker-build` and `docker-push`.  I saw some pipelineRefs in `.tekton` named `docker-build`.  Should those be renamed too?
> feat: enable podman support in Makefile

- .github/workflows/codecov.yml
There is an error `/pkg/cached/cache.go:242:16: undefined: atomic.Pointer` in `build-and-deploy` recently https://github.com/redhat-appstudio/integration-service/actions/workflows/codecov.yml started from https://github.com/redhat-appstudio/integration-service/actions/runs/5287590372/jobs/9568263408
Update go in codecov.yml to 1.19 can fix it.
> chore: update go to 1.19 in codecov.yml

- controllers/pipeline/pipeline_adapter.go
- controllers/pipeline/pipeline_adapter_test.go
- gitops/snapshot.go
Copy build labels/annotations prefixed with build.appstudio from pipeline runs to new Snapshots
> feat(STONEINTG-454): copy build labels/annotations to new Snapshots

- config/rbac/role.yaml
- controllers/pipeline/pipeline_adapter.go
- controllers/pipeline/pipeline_adapter_test.go
- controllers/pipeline/pipeline_controller.go
- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
- controllers/snapshot/snapshot_controller.go
* As an object can have only one owner reference on controlled, so we change to make environment own binding on controlled.
* add err.Error() to reason when marking snapshot as invalid
* add rbac for environments/finalizers
* update log message
> feat(STONEINTG-484): set environment as owner reference of binding

- gitops/binding.go
- gitops/gitops_test.go
Remove the replica configuration from the component.Spec of SnapshotEnvironmentBinding. [See]([RHTAPBUGS-173](https://issues.redhat.com/browse/RHTAPBUGS-173)).
> fix(stoneintg-499):  remove replica configuration from SEB

- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
- loader/loader.go
- loader/loader_mock.go
- loader/loader_mock_test.go
- loader/loader_test.go
The integration service added a list of components to the SnapshotEnvironmentBinding upon creation.  Prior to this change the list was derived from the Application associated with the snapshot. This changes makes the integration service derive the components from the snapshot itself.
> fix(stoneintg-505): Use snapshot components when creating SEB

- controllers/pipeline/pipeline_adapter.go
- controllers/pipeline/pipeline_adapter_test.go
- helpers/integration.go
Logic for the EnsureEphemeralEnvironmentsCleanedUp function within the pipeline_adapter has been moved to a helper function to allow for use by the SnapshotEnvrionmentBinding.
See [this PR](https://github.com/redhat-appstudio/integration-service/pull/228) or [STONEINTG-433](https://issues.redhat.com/browse/STONEINTG-433) for motivation.
> fix(STONEINTG-433): refactor EnsureEphemeralEnvironmentsCleanedUp

- controllers/binding/snapshotenvironmentbinding_adapter.go
- controllers/binding/snapshotenvironmentbinding_adapter_test.go
- controllers/binding/snapshotenvironmentbinding_controller.go
- gitops/binding.go
- gitops/predicates.go
- gitops/predicates_test.go
- helpers/integration.go
When an issue happens with deployment of the Snapshot during Integration testing on ephemeral environments, the Integration service needs to delete the associated Environment and DTC CRs in order to clean up the provisioned namespace.
> feat(STONEINTG-433): cleanup ephemeral envs for some errors

- controllers/binding/snapshotenvironmentbinding_adapter.go
- controllers/pipeline/pipeline_adapter.go
- controllers/scenario/scenario_adapter.go
- controllers/snapshot/snapshot_adapter.go
Read the code about `RequeueRequest`, `CancelRequest` and `error` in [ReconcileHandler(operations []ReconcileOperation)](https://github.com/redhat-appstudio/operator-goodies/blob/main/reconciler/handler.go#L23-L35), according to the definitions of [RequeueWithError(error)](https://github.com/redhat-appstudio/operator-goodies/blob/main/reconciler/results.go#L45) and [RequeueOnErrorOrStop(error)](https://github.com/redhat-appstudio/operator-goodies/blob/main/reconciler/results.go#L75), these two functions are the same when the `error` is not `nil`, that is to `requeue`.
1. Replace `RequeueOnErrorOrStop(error)` with `RequeueWithError(error)` when error is not `nil` to be consistent in all  adapters
2. Call `RequeueWithError(err)` when failing to update scenario to requeue
Signed-off-by: …
> feat(STONEINTG-483): add requeueDelay to ensure* functions

- controllers/pipeline/pipeline_adapter.go
- controllers/snapshot/snapshot_adapter.go
- gitops/snapshot.go
- gitops/snapshot_test.go
1. Added new Snapshot status "ErrorOccured" and replaced "Invalid" status in the snapshot controller logic with it.
2. Moved the RegisterNewSnapshot() function from NewSnapshot() to the place following a.client.Create(a.context, *Snapshot) action
> fix(STONEINTG-469): add SetSnapshotIntegrationStatusAsInvalidandNoRequ

- .tekton/push.yaml
- config/grafana/dashboard.yaml
as part of this bug fix and the upgrade to `GrafanaOperator` v5, we have to update the `GrafanaDashboard` resource to match the new api
More details:
https://redhat-internal.slack.com/archives/C02CTEB3MMF/p1690371680784569
The dashboard is still presenting data due to a patch we merged to RHTAP, and it will be removed after these changes will be merged
> fix(RHTAPWATCH-8): Update GrafanaDashboard to match GrafanaOperator v5

- .tekton/pull-request.yaml
- .tekton/push.yaml
Recently the RHTAP CI check in all the service repos ([including our PRs](https://github.com/redhat-appstudio/integration-service/pull/257/checks?check_run_id=15561250086)) started failing with a similar error as shown below:
```
Error retrieving pipeline for pipelinerun tekton-ci/integration-service-pull-request-8mdtv: failed to get pipeline:
error requesting remote resource: error getting "bundleresolver" "tekton-ci/bundles-2eaa2963a940eb40a21b75a6baacc12b":
could not find object in image with kind: Task and name: docker-build
```
This is due to some recent changes in the PipelineRun definition in the tekton-ci, where we'd need to specify the bundles inside a resolver format and also specifically mention the `kind: Pipeline` (by default it would pick up the value `Task` and that …
> chore(ci): add workaround for new OSP ver

- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
This PR is to add a fix for copying build labels/annotations from the Snapshots to the integration test PLRs
> fix(STONEINTG-508): copy build labels/annotations to the intg test PLR

- controllers/buildpipeline/buildpipeline_adapter.go
- controllers/buildpipeline/buildpipeline_adapter_test.go
- controllers/buildpipeline/buildpipeline_controller.go
- controllers/buildpipeline/buildpipeline_controller_test.go
- controllers/buildpipeline/buildpipeline_suite_test.go
- controllers/controllers.go
- controllers/integrationpipeline/integrationpipeline_adapter.go
- controllers/integrationpipeline/integrationpipeline_adapter_test.go
- controllers/integrationpipeline/integrationpipeline_controller.go
- controllers/integrationpipeline/integrationpipeline_controller_test.go
- controllers/integrationpipeline/integrationpipeline_suite_test.go
- controllers/snapshot/snapshot_adapter_test.go
- gitops/snapshot.go
- gitops/snapshot_test.go
- helpers/integration_test.go
- loader/integration_test.go
- loader/loader_test.go
* split pipeline controller to build and test pipeline controller
* move func PrepareSnapshot() to gitops pkg and refactor it
* rename the pipelinerun variable in unittest to buildPipelineRun
or integrationPipelineRun
> feat(STONEINTG-493): split pipeline controller to 2 new controller

- controllers/binding/snapshotenvironmentbinding_adapter.go
- controllers/binding/snapshotenvironmentbinding_adapter_test.go
- controllers/binding/snapshotenvironmentbinding_controller.go
- docs/binding-controller.md
- gitops/binding.go
- gitops/binding_test.go
- gitops/predicates.go
- gitops/predicates_test.go
* The HaveBindingsFailed function was using the wrong condition ComponentDeploymentConditions, changed it to use BindingConditions
* Add additional checks to ensure that EnsureIntegrationTestPipelineForScenarioExists executes correctly
* Add IntegrationSnapshotEnvironmentBindingPredicate to the binding controller to ensure that individual predicates don't filter SEBs that are not for Integration testing
* Cover more of gitops/binding.go with dedicated file
* Add test coverage for updated IsBindingDeployed and HaveBindingsFailed functions
> fix(STONEINTG-565): change the condition for HaveBindingsFailed

- .github/.kube-linter-config.yaml
- .github/workflows/pr.yaml
Kube lint checks for flaws in kubernetes resource definitions
> chore(CI): add kube-lint

- controllers/integrationpipeline/integrationpipeline_adapter.go
- controllers/integrationpipeline/integrationpipeline_adapter_test.go
- controllers/snapshot/snapshot_adapter.go
- gitops/snapshot.go
- gitops/snapshot_test.go
Added checking before the status of snapshot is updated to avoid repetition action
After the snapshot is set to Invalid status, return immediately and avoid to be set to "Passed" or " Failed" again.
> fix(STONEINTG-469): fix the negative number in SnapshotConcurrentTotal

- controllers/integrationpipeline/integrationpipeline_controller_test.go
Integration PLR has a wrong type label in the test suite.
> fix(unitest): integrationpipline has wrong type

- .tekton/push.yaml
Temporary disable grafana updates into infra-deployments due to non-technical reasons.
Devs must link grafana changes manaully now
> chore(grafana): don't update grafana in infra-deployments

- .github/.kube-linter-config.yaml
- config/default/manager_auth_proxy_patch.yaml
- config/manager/manager.yaml
Security improvement, containers are not supposed to write to root filesystem
> fix(STONEINTG-566): run container with read-only root filesystem

- controllers/binding/snapshotenvironmentbinding_adapter.go
- controllers/binding/snapshotenvironmentbinding_adapter_test.go
- docs/binding-controller.md
It is not possible to know whether an ephemeral SEB is in an unrecoverable state.  This change implements a workaround wherein if an SEB still has the 'ErrorOccured' condition set to 'True' after five minutes the SEB will be assumed to be unrecoverable and will be cleaned up.
> feat(stoneintg-586): add timeout to detect ephemeral SEB errors

- controllers/integrationpipeline/integrationpipeline_adapter.go
- helpers/integration.go
- helpers/integration_test.go
- status/format_test.go
- status/reporters.go
= Created new function to provide test outcome =
Test outcome is now strcuture which also keeps results for further
processing
In reporters.go this function was called even only half of it was needed
as check if pipeline finished is before this call
= Removing log from task result getter =
Usefulness of this log entry is questionable, getter either returns
result or not, we don't have to log result there.
If log is needed, higher function should do it, not getter.
This also simplifies tests and code as we don't need to pass logger into
such low level structure for single use.
= Removal of excessive logging =
Now only integrationpipeline controller logs status of integration test,
a lot fo log duplication has been avoided by removing logging from
helper functions.
This contoller is also …
> fix(STONEINTG-523): refactor get pipeline outcome method

- .github/workflows/pr.yaml
1. Use ubuntu directly with removing fedora container
2. Update the task to check the whole dir and remove duplicated task
> fix(STONEINTG_587): check kubernetes manifests is not working

- gitops/snapshot.go
- gitops/snapshot_test.go
Add checking and update the log message in CanSnapshotBePromoted() in case there are no integration tests
> fix(STONTEINTG-573): fix confusing message about failed test

- gitops/snapshot.go
- gitops/snapshot_integration_tests_status.go
- gitops/snapshot_integration_tests_status_test.go
- gitops/snapshot_test.go
Functions and data types to manipulate with status of test scenarios in snapshots.
Annotation test.appstudio.openshift.io/status is used to keep metadata about integration tests in snapshots. This commit provides functions to manipulate with them: udpating, deleting, writing, reading statuses
Example:
```
test.appstudio.openshift.io/status: [
{
"scenario": "scenario-1",
"status": "EnvironmentProvisionError",
"timestamp": "2023-07-26T16:57:49+02:00",
"details": "Failed ..."
}
]
```
> feat(STONEINTG-523): functions to manipulate with test status

- gitops/snapshot_integration_tests_status_test.go
Sometimes test is too quick and the timestamp is the same as before update.
Adding sleep explictily to make sure timestamp differs
> fix(STONEINTG-523): test race condition with timestamps

- status/reporters.go
* update NS of pipelines-as-code secret since the NS has been changed to openshift-pipelines
> fix(STONEINTG-524): update NS of pipelines-as-code secret

- config/grafana/dashboards/integration-service-dashboard.json
> feat: additional SLI dashboards in grafana

- controllers/buildpipeline/buildpipeline_adapter.go
- gitops/snapshot_integration_tests_status.go
- gitops/snapshot_integration_tests_status_test.go
- go.mod
- go.sum
We have a regression because function AddAnnotations is only adding new annotations to objects, existing annotations are not updated.
We need to update existing annotations, thus using SetAnnotation function from newer version of operator-toolkit repo.
> fix(STONEINTG-523): use SetAnnotation function

- controllers/integrationpipeline/integrationpipeline_adapter.go
- controllers/integrationpipeline/integrationpipeline_adapter_test.go
- controllers/snapshot/snapshot_adapter.go
- gitops/snapshot.go
- gitops/snapshot_predicate_test.go
- gitops/snapshot_test.go
> style: fix spelling of Succeeded

- controllers/binding/snapshotenvironmentbinding_adapter.go
- controllers/binding/snapshotenvironmentbinding_adapter_test.go
We don't need so many logs about failed SEB provisioning, it floods logs with repetetive errors.
> fix(STONEINTG-611): stop extensive logging about failed SEB

- config/grafana/dashboards/integration-service-dashboard.json
Previously empty values in the violations graphs were reported as zero.  This is because in order to calculate the percentage of requests meeting our thresholds we divide the "good" requests by the total requests.  If there are no total requests then grafana sets 0/0 to 0 rather than dividing by 0.  This change ignores the empty values and changes the display from a line to bars to improve readability.
> fix(stoneintg-564): ignore empty values

- controllers/binding/snapshotenvironmentbinding_adapter.go
- gitops/binding.go
- gitops/binding_test.go
- metrics/integration.go
- metrics/integration_test.go
Add metric for measuring the time between SEB is created and SEB is ready to use
> feat(STONEINTG-534): add SLI for measuring time from SEB created to ready

- controllers/binding/snapshotenvironmentbinding_adapter.go
- controllers/binding/snapshotenvironmentbinding_adapter_test.go
- controllers/integrationpipeline/integrationpipeline_adapter.go
- controllers/integrationpipeline/integrationpipeline_adapter_test.go
- controllers/integrationpipeline/integrationpipeline_controller.go
- controllers/integrationpipeline/integrationpipeline_controller_test.go
- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
- docs/binding-controller.md
- docs/integration_pipeline_controller.md
- docs/snapshot-controller.md
- gitops/binding.go
- gitops/binding_test.go
An annotation (test.appstudio.openshift.io/status) is added to snapshot and updated when condition of integration tests changes.
This annotation contains metadata of all tests which have been created for the particular snapshot.
Example:
```
test.appstudio.openshift.io/status: [
{
"scenario": "scenario-1",
"Status": "EnvironmentProvisionError",
"timestamp": "2023-07-26T16:57:49+02:00",
"details": "Failed ..."
}
]
```
> feat(STONEINTG-523): Report status of integration tests into snapshot

- controllers/binding/snapshotenvironmentbinding_adapter.go
- controllers/integrationpipeline/integrationpipeline_adapter.go
- controllers/snapshot/snapshot_adapter.go
- gitops/snapshot.go
- gitops/snapshot_test.go
Snapshot which is already failed shouldn't be updated to keep original failure time.
First commit addresses the issue.
Second commit does refactoring to improve readability
> fix(seb-controller): don't set failed status to already failed snapshot

- config/grafana/dashboards/integration-service-dashboard.json
There is missing `,` in one line, probably caused by merging PR in paralel.
> fix(grafana): fix JSON format

- controllers/controllers.go
- controllers/integrationpipeline/integrationpipeline_adapter_test.go
- controllers/statusreport/statusreport_adapter.go
- controllers/statusreport/statusreport_adapter_test.go
- controllers/statusreport/statusreport_controller.go
- controllers/statusreport/statusreport_controller_test.go
- controllers/statusreport/statusreport_suite_test.go
- docs/statusreport-controller.md
- git/github/github.go
- git/github/github_test.go
- gitops/snapshot.go
- gitops/snapshot_predicate.go
- gitops/snapshot_predicate_test.go
- status/reporters.go
- status/reporters_test.go
- status/status.go
- status/status_test.go
* Create function to get credential from snapshot
* Create function to report for result of handle ITSes for snapshot
* The old [EnsureStatusReported()](https://github.com/redhat-appstudio/integration-service/blob/main/controllers/integrationpipeline/integrationpipeline_adapter.go#L177) in integration pipeline controller is kept since we don't know yet how to get the test result for integration pipeline runs after [PLNSRVCE-1295](https://issues.redhat.com/browse/PLNSRVCE-1295)
* The controller will get all checkRuns and then compare with the checkRun to be created/updated to if the action is needed before performing the action
* The controller will get all commitStatuses and then compare with the commitStatus to be created to see if the action is needed before performing the action
* The …
> feat(STONEINTG-524): Report result of handling ITS to github in a new controller

- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
* Create new patch before updating status to prevent update conflicts
* Update unit tests to catch such failure in case of regression
> fix(STONEINTG-581): global candidate list update conflict

- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
- tekton/integration_pipeline.go
- tekton/integration_pipeline_test.go
Copies any App Studio annotations, ones that contain the string `appstudio.openshift.io/` in their key, to the Tekton PipelineRun.
Ref. https://issues.redhat.com/browse/HACBS-2548
> feat: copy App Studio annotations from ITS to PR

- controllers/snapshot/snapshot_controller.go
- controllers/snapshot/snapshot_controller_test.go
- helpers/errorhandlers.go
If the snapshot component cannot be found, we should retry.  If it still cannot be found the snapshot should not be requeued.  This change adds retries to the controller and does not signal the controller to retry if the component cannot be found.
> fix(stoneintg-579): do not requeue snapshot if component cannot be found

- config/grafana/dashboards/integration-service-dashboard.json
- controllers/snapshot/snapshot_adapter.go
- gitops/snapshot.go
- gitops/snapshot_test.go
- metrics/integration.go
- metrics/integration_test.go
new metric release latency seconds
new grafana panel of same name
measures latency between integration tests
completing and release creation
> feat: new grafana panel for release latency seconds

- helpers/integration.go
- helpers/integration_test.go
Integration-service must accept checks with warnings as passed tests. Warning is not a failure.
> fix(STONEINTG-632): accept warning test result as passed

- config/rbac/role.yaml
- controllers/component/component_adapter.go
- controllers/component/component_adapter_test.go
- controllers/component/component_controller.go
- controllers/component/component_controller_test.go
- controllers/component/component_suite_test.go
- controllers/component/predicates.go
- docs/component_controller.md
- gitops/snapshot.go
Creation of component controller to watch for component deletion events. When a component is deleted, IS will create a new snapshot to reflect those changes as well as update snapshotenvironmentbindings.
> feat(STONEINTG-488): react to application component deletion

- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
- docs/snapshot-controller.md
- gitops/snapshot.go
- gitops/snapshot_test.go
* Add AutoRelease status condition to Snapshots to mark if Snapshot was previously auto-released
* Add DeployedtoRootEnvironments status condition to Snapshots to mark if Snapshot was deployed to all root environments
* Add AddedToGlobalCandidateList status condition to Snapshot to mark if Snapshot component was added to the Global Candidate List
* Set the above conditions in the snapshot_adapter where appropriate
* Add unit tests for the above changes
> fix(STONEINTG-631): add release, deployment, GCL status conditions

- controllers/snapshot/snapshot_controller.go
- helpers/errorhandlers.go
Changes part of the fix merged in #329.  Just turns `HandleLoaderError` into a function rather than a method.
> hotfix: remove HandleLoaderError from logger struct

- controllers/binding/snapshotenvironmentbinding_controller.go
- controllers/binding/snapshotenvironmentbinding_controller_test.go
- helpers/errorhandlers_test.go
Ordinarilly if the snapshot associated with an SEB cannot be found we fail and requeue the reconciliation for that SEB.  This change adds retries to the retrieval of the Snapshot and does away with the requeue if it cannot be found.  This way if the user deletes a snapshot the SEB will not be permanently stuck in a reconcile state.
> fix(stoneintg-582): do not requeue SEB if snapshot cannot be found

- controllers/binding/snapshotenvironmentbinding_controller.go
- controllers/binding/snapshotenvironmentbinding_controller_test.go
Ordinarilly if the application associated with an SEB cannot be found we fail and requeue the reconciliation for that SEB.  This change adds retries to the retrieval of the application and does away with the requeue if it cannot be found.  This way if the user deletes an application the SEB will not be permanently stuck in a reconcile state.
> fix(stoneintg-584): do not requeue SEB if application cannot be found

- config/grafana/dashboards/integration-service-dashboard.json
Grafana display incorrect for Latency Release Creation in Seconds panel
- [x ] Commit messages are descriptive enough ([hints](https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/))
> fix(STONEINTG-532): correct panel display release create

- controllers/statusreport/statusreport_adapter.go
- controllers/statusreport/statusreport_adapter_test.go
Adding feature flag FEATURE_STATUS_REPORTING_ENABLED to enable feature for reporting tests statuses into pull requestes. Featue is not ready yet, thus is disabled by default.
> feat(statusreporting): add feature flag

- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
Making `EnsureCreationOfEnvironments` reusable for single test creation.
`ensureEphemeralEnvironmentForScenarioExists` contains refactored part that allows to ensure existence of ephemeral env for single scenario
> refactor(STONEINTG-539): EnsureCreationOfEnvironments

- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
> fix(STONEINTG-585): update owner reference to snapshot for SEBs

- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
- controllers/snapshot/snapshot_controller.go
- docs/snapshot-controller.md
Make cleaner which function is responsbile for what in snapshot adapter.
> refactor(STONEINTG-539): update wording for ephemeral environments

- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
Logger is causing segfault from `snapshotEnvironmentBinding.Spec.Environment`, because updateExistingSnapshotEnvironmentBindingWithSnapshot may return nil pointer when patching failed, and logger tries to access to struct values of nil pointer.
At first that function doens't need to return pointer, because it already received a pointer as parameter, and it's exactly the same pointer.
Also unittest has been updated to test, if resource has been really patched.
Segfault traceback:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x118 pc=0x180b176]
goroutine 1638 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1() …
```
> fix(updateExistingSnapshotEnvironmentBindingWithSnapshot): segfault

- docs/pull_request_template.md
> chore: add link to codecov in PR template

- api/v1alpha1/integrationtestscenario_conversion.go
* This fix resolves the issue when converting v1alpha1 to v1beta1 IntegrationTestScenarios where the status.conditions is not added to the converted resource, resulting in the "scenario is invalid: status.conditions: Required value" error
> fix(STONEINTG-583): add status conditions when converting to v1beta1

- .github/workflows/size.yaml
Add labels with PR size into PRs based on number of changed lines
> chore(workflow): mark size of PRs

- controllers/integrationpipeline/integrationpipeline_adapter.go
- controllers/integrationpipeline/integrationpipeline_adapter_test.go
- controllers/integrationpipeline/integrationpipeline_controller.go
- controllers/statusreport/statusreport_adapter.go
- controllers/statusreport/statusreport_adapter_test.go
- controllers/statusreport/statusreport_controller.go
- docs/statusreport-controller.md
- git/github/github.go
- git/github/github_test.go
- status/format.go
- status/format_test.go
- status/reporters.go
- status/reporters_test.go
- status/status.go
- status/status_test.go
* remove status report from integrationPLR controller
* create comment to PR in statusreport controller for github webhook
* add test result to report of statusreport
* update comment if there is one existing comment of snapshot and scenario test status
* update controller diagram
checkRun example: https://github.com/hongliuorg/devfile-sample-go-basic/pull/4/checks?check_run_id=16776195643
commitStatus/comment example: https://github.com/hongweiliu17/devfile-sample-go-basic/pull/2
> feat(STONEINTG-613): remove status report from PLR controller

- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
- gitops/binding.go
- gitops/binding_test.go
- loader/loader.go
- loader/loader_mock.go
- loader/loader_mock_test.go
- loader/loader_test.go
* Refactor NewBindingComponents to take components directly from the Snapshot and convert them into bindingComponents by referencing them by the `metadata.name` instead of `spec.componentName`.
* This removes the need for the extra step of fetching Components from the cluster
* Remove the GetAllSnapshotComponents function altogether as it is unused after the above changes
* Remove the now unused components parameter from functions which were creating/updating SEBs
> fix(STONEINTG-641): use snapshot for SEB components directly

- config/default/manager_auth_proxy_patch.yaml
* Mitigation for CVE-2023-44487
* Disable http2 via --http2-disable flag in kube-rbac-proxy options
> fix(STONEINTG-666): update kube-rbac-proxy to v0.15.0

- docs/integration_pipeline_controller.md
This PR is triggered by a [discussion within a PR](https://github.com/redhat-appstudio/integration-service/pull/341#discussion_r1374533710).
* This commit removes the "Report status if Snapshot..." node from the integration_pipeline diagram.
* Because integrationpipeline controller is not responsible for reporting statuses for PR events.
* This is the responsiblity of statusreport controller. It's diagram is correct.
> docs: remove unnecessary node

- controllers/scenario/scenario_adapter.go
- controllers/scenario/scenario_adapter_test.go
* Change the condition for seting scenario status to valid. The previous condition would return false if the condition was not present, so it would not work for scenarios that were created for e2e or load testing
* See [IsStatusConditionFalse](https://pkg.go.dev/github.com/coderanger/controller-utils/conditions#IsStatusConditionFalse) for more context - it returns false if status condition is not present
> fix(STONEINTG-583): set scenario status to valid if undefined

- config/grafana/dashboards/integration-service-dashboard.json
SEB created to ready timeseries panel
SEB created to ready violations panel
> feat(STONEINTG-536): add 2 panels for SLO 6

- docs/build_pipeline_controller.md
- tekton/predicates.go
- tekton/predicates_test.go
- tekton/utils.go
This commit changes the controller to no longer wait for the PipelineRun to have the annotation `chains.tekton.dev/signed` be set to the value of `"true"`. Instead, it now only waits for the annotation to be set regardless of its value. This indicates the Chains controller is done processing the PipelineRun and the integration service should move on.
This prevents Chains failures from causing integration tests to never run. Instead, let the integration tests run, and verification tools, e.g. Enterprise Contract, report on unsigned artifacts.
> feat(EC-202): Proceed if Chains could not sign

- controllers/buildpipeline/buildpipeline_controller.go
- controllers/integrationpipeline/integrationpipeline_adapter.go
- controllers/integrationpipeline/integrationpipeline_adapter_test.go
- controllers/integrationpipeline/integrationpipeline_controller.go
* Stop fetching the component in integrationpipeline controller because integration pipelineRuns do not necessarily need to reference a component in their labels - e.g. ones created to test composite Snapshots
* Move SetupApplicationComponentCache to the buildpipeline controller to align with the above change
* Update controller and adapter tests accordingly
> fix(STONEINTG-649): remove component in integrationpipeline controller

- status/reporters.go
- status/reporters_test.go
* Add support for the `Deleted` state in the status reporters, mapping it to report as an error/failure and adding the explanation for the issue in the summary
Example comment:
> fix(STONEINTG-668): update the status reporter with new "Deleted" state

- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
- helpers/errorhandlers.go
- helpers/errorhandlers_test.go
* stop reconciliation if the env defined in ITS doesn't exist
> fix(STONEINTG-642) stop reconciliation if env is not found for ITS

- controllers/binding/snapshotenvironmentbinding_adapter_test.go
- controllers/buildpipeline/buildpipeline_adapter_test.go
- controllers/component/component_adapter_test.go
- controllers/integrationpipeline/integrationpipeline_adapter_test.go
- controllers/snapshot/snapshot_adapter_test.go
- controllers/statusreport/statusreport_adapter_test.go
- loader/loader.go
- loader/loader_mock.go
- loader/loader_mock_test.go
* add more unittest in snapshot adapter to increase code coverage by creating data
* migrate to use  operator-toolkit loader
* one example to use toolkit.GetObject(name, namespace string, cli client.Client, ctx context.Context, object client.Object) instead of client.Get()
https://docs.google.com/document/d/1_hMZaaRZFnTm6dXb7mC6GWHgu7WnR4Pc1Du-Rj8zwLk/edit#heading=h.42ifznjra9qa is created as a reference to add UT
> feat(STONEINTG-635): increase snapshot code coverage

- gitops/snapshot_predicate_test.go
Unittest works directly with objects, there is no need for saving them in k8s DB
> fix(snapshot_predicate_test): remove unneeded provisioning

- controllers/buildpipeline/buildpipeline_adapter.go
- controllers/buildpipeline/buildpipeline_adapter_test.go
- controllers/buildpipeline/buildpipeline_controller.go
- controllers/buildpipeline/buildpipeline_controller_test.go
- docs/build_pipeline_controller.md
- go.mod
- helpers/integration.go
- tekton/predicates.go
- tekton/predicates_test.go
Because of the introduction of more aggressive resource pruning in RHTAP, the integration service must add finalizers to build pipeline runs when they are created.  This will ensure that the integration service can create snapshots of for successful builds.  Once the snapshot is created the finalizer will be removed so that the resource can be cleaned up.
> feat(stoneintg-600): Add finalizers to build pipeline runs

- controllers/binding/snapshotenvironmentbinding_adapter.go
- metrics/integration.go
- metrics/integration_test.go
> feat(stoneintg-628): metric for time to start plr with ephemeral env

- config/grafana/dashboards/integration-service-dashboard.json
Add histogram to show the latency between the time a snapshot is created and the time a pipelineRun is created for pipelineRuns with ephemeral environments
> feat(stoneintg-628): add histogram panels for pipelinerun latency

- config/grafana/dashboards/integration-service-dashboard.json
- metrics/integration.go
change name of latency release creation metric by prefixing with integration_service. Bug fix related to [stoneintg-561](https://issues.redhat.com//browse/stoneintg-561)
- [x ] Commit messages are descriptive enough ([hints](https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/))
> fix(STONEINTG-561): bug in naming convention of metrics

- .github/workflows/size.yaml
Just adding unittests makes PR size XL. Increasing thresholds by ~20% to make better estimations.
> fix(size): add 20% to thresholds

- controllers/integrationpipeline/integrationpipeline_adapter.go
- controllers/integrationpipeline/integrationpipeline_adapter_test.go
- controllers/integrationpipeline/integrationpipeline_controller.go
- controllers/integrationpipeline/integrationpipeline_controller_test.go
* Add the Snapshot to the integrationpipeline adapter
* If the integrationpipeline controller cannot find the Snapshot for that pipelineRun, remove the finalizer for it and let the ownerReference cascading delete it
> fix(STONEINTG-684): remove finalizers if Snapshot can't be found 

- config/grafana/dashboards/integration-service-dashboard.json
Make SLI title explicitly mention static environments
> fix(grafana): update SLI title for static env

- controllers/buildpipeline/buildpipeline_adapter_test.go
- controllers/buildpipeline/buildpipeline_controller_test.go
* Don't start the controller manager in the controller test suite because that causes it to react to creation events in adapter unit tests and causes collisions when it attempts to add a finalizer to all newy created build pipelineRuns
* Wait for the buildPipeline run resource on the control plane to be fully updated and its finalizer removed before ending finalizer tests to prevent create actions in beforeEach from running into conflicts
* Reduce update actions for build pipelineRuns where they don't require testing resources on the control plane
> fix(STONEINTG-693): stop collisions in buildpipeline adapter tests

- status/reporters.go
If we fail to create object with *StatusAdapter, we should skip update of PR status. This error is usually non-recoverable it only retriggers reconciliation and blocks other updates.
> fix(STONEINTG-689): skip update if *StatusAdapter fails

- controllers/binding/snapshotenvironmentbinding_adapter.go
Integration PLRs created with ephemeral environments are missing build labels and annotation. PLR created in static envs have them copied.
> fix(binding-PLR): missing build labels/annotations

- controllers/binding/snapshotenvironmentbinding_adapter.go
- controllers/snapshot/snapshot_adapter.go
- gitops/snapshot.go
- metrics/integration.go
We want to measure only perfomance of automatic creation of PLR after snapshot is created. Manual reruns can be triggered after days and week and gives no usable value for this metric.
Separated counting of created PLRs from measurement of how long it took.
There was also a missing PLR counter in SEB controller.
> fix(metrics): don't count PLR re-run into statistics

- controllers/binding/snapshotenvironmentbinding_controller_test.go
- controllers/component/component_controller_test.go
- controllers/integrationpipeline/integrationpipeline_controller_test.go
- controllers/scenario/scenario_controller_test.go
- controllers/snapshot/snapshot_controller_test.go
- controllers/statusreport/statusreport_controller_test.go
* Don't start the controller manager in the controller test suite because that causes it to react to creation events in adapter unit tests and causes potential collisions and unexpected behavior
> fix(STONEINTG-693): don't start controllers in unit tests

- controllers/buildpipeline/buildpipeline_adapter_test.go
- tekton/utils.go
- tekton/utils_test.go
Previously the git url for a PR job was set to the target branch, causing errors when pulling the revision to be tested. This change sets the git URL in the integration PLR to the source branch git url instead
> fix(rhtapbugs-975): point test plr params to source repo

- controllers/buildpipeline/buildpipeline_adapter.go
- controllers/buildpipeline/buildpipeline_adapter_test.go
- controllers/buildpipeline/buildpipeline_controller.go
- controllers/component/component_controller.go
Update the component controller log message that is outputted when a build pipeline could not be found.  The new log message is outputted as 'INFO' rather than 'ERROR' and contains more information
> fix(stoneintg-645): failed to get component for build pipeline

- controllers/binding/snapshotenvironmentbinding_adapter.go
SEB was not marking snapshot as in-progress. Fixing parity with static env tests.
> fix(SEB): mark snapshot as running tests

- status/reporters.go
CheckRun and CommitReporters can be separated into different structs with implementing common interface, to make easier to understand relations and avoid duplicated code.
It makes readability better.
> refactor(reporters): separate github reporters

- controllers/buildpipeline/buildpipeline_adapter_test.go
- tekton/utils.go
- tekton/utils_test.go
> Revert "fix(rhtapbugs-975): point test plr params to source repo"

- api/v1beta1/integrationtestscenario_types.go
- config/crd/bases/appstudio.redhat.com_integrationtestscenarios.yaml
Instead of typying full name IntegrationTestScenario, we can just use `its`.
```
oc get its
NAME           APPLICATION
example-pass   application-sample
```
> feat(api): add shortname for ITS

- status/reporters.go
> feat(STONEINTG-608): switch to use integration-service  PAC secret

- controllers/snapshot/snapshot_controller_test.go
- controllers/statusreport/statusreport_controller_test.go
* Add eventually blocks for controller unit tests that check ignoring restored Snapshots
> fix(STONEINTG-692): wait for backup labels in unit tests

- controllers/statusreport/statusreport_adapter.go
- controllers/statusreport/statusreport_adapter_test.go
- git/github/github.go
- git/github/github_test.go
- gitops/snapshot.go
- gitops/snapshot_test.go
- status/reporters.go
- status/reporters_test.go
> fix(STONEINTG-689): add PR last update snapshot annotation

- controllers/statusreport/statusreport_adapter.go
- controllers/statusreport/statusreport_adapter_test.go
- gitops/snapshot.go
- gitops/snapshot_test.go
This PR to fix race condition when adding another IntegrationTestScenario to an application that already running former one, the new one will bot be triggered. 
to fix it, we identify the untriggered ITS  and then we add Re-run label to snapshot and this will trigger the snapshot reconcile .
more details in Jira [STONEINTG-646](https://issues.redhat.com/browse/STONEINTG-646)
> fix(STONEINTG-646):  trigger snapshot reconcile for added its

- .gitlint
- gitops/snapshot.go
- gitops/snapshot_test.go
* let gitlint ignore the prs from rhtap bot
* rename AppStudioTestSucceededConditionPassed to AppStudioTestSucceededConditionSatisfied to pass snyk test
The error caught by snyk to be fix is as below 
```
{
"ruleId": "go/HardcodedPassword",
"ruleIndex": 0,
"level": "warning",
"message": {
"text": "Do not hardcode passwords in code. Found hardcoded saved in AppStudioTestSucceededConditionPassed.",
"markdown": "Do not hardcode passwords in code. Found {0} saved in {1}.",
"arguments": [
"[hardcoded](0)",
"[AppStudioTestSucceededConditionPassed](1)"
]
},
"locations": [
{
"physicalLocation": {
"artifactLocation": {
"uri": "gitops/snapshot.go",
"uriBaseId": "%SRCROOT%"
},
"region": {
"startLine": 197,
"endLine": 197,
"startColumn": 12,
"endColumn": 49
}
}
}
...
Task sast-snyk-check failed …
```
> feat(STONEINTG-696): Issue fixes to onborad integration-service to RHTAP

- .gitlint
let gitlint ignore pr from rhtap bot `red-hat-trusted-app-pipeline`, refer to this [pr](https://github.com/redhat-appstudio/integration-service/pull/466) from `red-hat-trusted-app-pipeline`
> fix(STONEINTG-696): let gitlint ingore prs from red-hat-trusted-app-pipeline

- controllers/snapshot/snapshot_adapter.go
Currently the code counts time for created PLR even the pipeline hasn't been created. Only created pipelines shoulw be covered in metrics.
> fix(metrics): count only created integration PLR

- gitops/predicates.go
- gitops/predicates_test.go
* Update all gitops predicates to return false for creation, delete and generic events
> fix(STONEINTG-714): gitops predicates cover all types of events

- Dockerfile
The five labels as below are missing in integration-service docker image.  Add these label by referencing to [release-service](https://github.com/redhat-appstudio/release-service/blob/main/Dockerfile#L35-L38) and [build-service](https://github.com/redhat-appstudio/build-service/blob/main/Dockerfile#L32)  Docker image to pass EC verify.
* description
* io.k8s.description
* io.k8s.display-name
* summary
* io.openshift.tags
> fix(STONEINTG-696): add mandatory label to pass EC verify

- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
when creating release for snapshot
* retry for recoverable error
> feat(STONEINTG-725): retry for recoverable error when creating relase

- .tekton/integration-service-pull-request.yaml
- .tekton/integration-service-push.yaml
This should resolve the `"msg":"Required task \"source-build\" is missing"` EC failure.
> fix: set build-source-image pipeline param to true

- controllers/snapshot/snapshot_adapter.go
- gitops/snapshot.go
- gitops/snapshot_test.go
> feat(STONEINTG-703): reset snapshot status conditions when rerunning test

- .tekton/integration-service-pull-request.yaml
Update the tekton PR job to use source_url rather than repo_url for the git-url parameter.  This will ensure that the repo will clone from the source rather than the target when testing PR jobs
> fix(rhtapbugs-975): use source_url instead of repo_url

- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
Re-running test sceanrio was causing creation of duplicated PLR for integration test. Record PLR name into test status annotation immediatelly to prevent controller to create additional PLR.
Only scenarios in static environment were affected by this bug.
> fix(STONEINTG-742): don't trigger duplicated integration PLRs

- metrics/integration.go
I currently maintain a spreadsheet tracking the latency between snapshot creation time and PLR start time for scenarios that use ephemeral environments.  So far, five snapshots have taken 15-30 seconds and one has taken 30+ seconds.  This commit adds two new buckets: 30-45 and 45-60.  This will allow us to get a better idea of just how long ephemeral environments are taking to be created so that we can more accurately create an SLO for this SLI.
> feat: add additional buckets to sli 2b histogram

- controllers/binding/snapshotenvironmentbinding_adapter.go
- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
- gitops/snapshot.go
- gitops/snapshot_test.go
Reruns are causing wrong data in this metric, this metric is suitable only for automatic runs.
> fix(STONEINTG-706): don't record PLR starttime for reruns

- controllers/buildpipeline/buildpipeline_adapter.go
- controllers/buildpipeline/buildpipeline_adapter_test.go
- controllers/buildpipeline/buildpipeline_controller.go
- tekton/predicates.go
- tekton/predicates_test.go
Tekton keeps deleting PLRs in running status. Integration-service must react to deletion event, even if PLR is still in running status to prevent blocking of deletion by removing finalizer.
> fix(RHTAPBUGS-1091): react to deleted running build PLR

- controllers/buildpipeline/buildpipeline_adapter.go
- controllers/buildpipeline/buildpipeline_adapter_test.go
- helpers/build.go
Add an annotation to the build pipelineRuns that shows the current status of the snapshot associated (or that will be associated) with that build pipeline.  This will allow users to more easily find out if build pipelines are not being finalized because the snapshot quota has been reached
> fix(stoneintg-730): Add build PLR annotation for snapshot status

- controllers/buildpipeline/buildpipeline_adapter.go
- controllers/buildpipeline/buildpipeline_adapter_test.go
- controllers/statusreport/statusreport_adapter.go
- controllers/statusreport/statusreport_adapter_test.go
- gitops/snapshot.go
> feat(STONE-738): Copy labels+annotations to composite snapshot

- controllers/binding/snapshotenvironmentbinding_adapter.go
- controllers/binding/snapshotenvironmentbinding_adapter_test.go
- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
- controllers/snapshot/snapshot_controller.go
- controllers/statusreport/statusreport_adapter.go
- gitops/binding_test.go
- gitops/snapshot.go
- gitops/snapshot_test.go
- helpers/integration_test.go
- loader/loader_test.go
MarkSnapshot* functiond were returning the same pointer as they received in snapshot paramter. There is no need to return pointer if we pass pointer as paramereter.
Given the pointer was returned it could puzzle devs to expect that it's a newly allocated memory instead. This old-new pointer was even used inconsistently in code, it's just safer to remove it and make clear that original pointer is being used for data updates.
> refactor(MarkSnapshot*): don't return the same pointer

- controllers/buildpipeline/buildpipeline_adapter.go
- controllers/buildpipeline/buildpipeline_adapter_test.go
- helpers/errorhandlers.go
- helpers/errorhandlers_test.go
- tekton/utils.go
> fix(STONEINTG-709): add support missing info of build PLR error

- config/default/manager_auth_proxy_patch.yaml
- config/default/manager_config_patch.yaml
- config/default/manager_webhook_patch.yaml
- config/manager/manager.yaml
Kustomize is configured to add integration-service prefix to each name. However many objects had already integration-service prefix defined which lead into duplicated names like
`integration-service-integration-service-controller-manager`
This had also another side effect causing that pod name was longer than 63 characters and it was truncated
```
generateName: integration-service-integration-service-controller-manager-6c6c5dcb65-
name: integration-service-integration-service-controller-managerc8sww
```
Removing extra integration-service prefix will solve this issue.
> fix(ocp-names): shorten generated names

- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
Prior to this commit the integration service would requeue release creation indefinitely if it failed.  If a release quota was hit then releases would be backed up then be created all at once and overwhelm user workspaces with potentially no-longer-relevant releases.  This change sets a timeout of three hours for requeued releases, after which creating a release for that snapshot will fail.
> fix(stoneintg-753): requeue release creation until timeout

- status/reporters.go
- status/reporters_test.go
When we have nothing to report, we should avoid to waste resources, mainly authentication to github API.
> fix(STONEINTG-751): don't auth when there is nothing to report

- .github/.kube-linter-config.yaml
- Dockerfile
- config/manager/kustomization.yaml
Image doesn't have exposed ports for liveness and readiness probes.
Adding EXPOSE into image. Also changing tag of the image to latest as we don't use `next` anymore.
This also creates a chicken egg problem, where we have to build latest image first to make effect on kube-lint, sorry future generations, but this is the best effort/outcome ratio (once we move this check copletely into konflux, we can use currently built image there).
> fix(kube-lint): fix liveness-port check

- cmd/snapshotgc/snapshotgc.go
- cmd/snapshotgc/snapshotgc_suite_test.go
- cmd/snapshotgc/snapshotgc_test.go
- go.mod
- go.sum
Find all snapshots that are part of a release
> chore(RHTAPWATCH-729): get namespace release snapshots

- cmd/snapshotgc/snapshotgc.go
- cmd/snapshotgc/snapshotgc_test.go
Find all snapshots that are part of a SnapshotEnvironmentBinding
> chore(RHTAPWATCH-729): get namespace Bindings snapshots

- controllers/buildpipeline/buildpipeline_adapter.go
- controllers/buildpipeline/buildpipeline_adapter_test.go
- controllers/buildpipeline/buildpipeline_controller.go
- tekton/build_pipeline.go
> feat(STONE-734): stop reconcilation for not found applicaiton

- cmd/snapshotgc/snapshotgc.go
- cmd/snapshotgc/snapshotgc_test.go
- go.mod
Delete the snapshots that are on the list of snapshots to be garbage-collected.
Also changed the logging implementation in tests to use a buffer to
allow verifying a couple of things using the logs.
> chore(RHTAPWATCH-732): delete garbage collected snapshots

- controllers/component/component_adapter.go
- controllers/component/component_controller.go
- controllers/component/predicates.go
- controllers/scenario/scenario_adapter_test.go
- helpers/finalizers.go
- helpers/integration.go
- helpers/integration_test.go
Changes to predicate logic for component controller to react to update events as opposed to deletion events. Alongside the addition of a finalizer ensures that the component controller will be able to accomplish generation of new snapshot for remaining components before the resource is removed from the cluster.
> (STONEINTG-687): add finalizer to component controller

- .github/workflows/pr.yaml
This is a duplicated workflow, we are testing builds using konflux, we don't need this workflow
> chore(worklfows): remove docker build

- controllers/component/component_controller.go
- controllers/component/component_controller_test.go
When application was removed, we cannot do much and should stop reconciliation instead of retrying indefinitely.
> fix(STONEINTG-687): stop reconciliation when app is not found

- controllers/buildpipeline/buildpipeline_adapter.go
- controllers/buildpipeline/buildpipeline_adapter_test.go
- helpers/integration.go
- tekton/build_pipeline.go
* remove finalizer after annotating build PLR
* annotate build PLR with successful only when the real snapshot is created
* requeue when failing to annotate build PLR or remove finalizer
* a few other small fixes
> fix(STONEINTG-779): fixes for annotating build PLR

- .gitlint
The user for Konflux reference updates has changed and is now failing gitlint checks. See #553
> chore: add red-hat-konflux to gitlint ignore list

- metrics/integration.go
We are often hit bucket 30 seconds, we need more datapoints to see, how much over 30 we are actually with reponse.
> fix(metrics): add more buckets into response metric

- Dockerfile
Modify the dockerfile so that snapshotgc is built and included inside the container image
> feat(RHTAPWATCH-777): add snapshotgc to image

- controllers/buildpipeline/buildpipeline_adapter.go
- controllers/buildpipeline/buildpipeline_adapter_test.go
- loader/loader.go
- loader/loader_mock.go
- loader/loader_mock_test.go
- loader/loader_test.go
- tekton/build_pipeline.go
* Stop finding matching Snapshots by comparing the contents of existing ones when determining if a new Snapshot needs to be created for a given build pipelineRun
* Switch to using the Snapshot annotation on the build pipelineRun, and also attempt to find Snapshots that are labeled for that PLR as a backup
* Add GetAllSnapshotsForBuildPipelineRun loader function to facilitate the above
> fix(STONEINTG-798): use labels to find Snapshots for build pipelineRun

- controllers/integrationpipeline/integrationpipeline_adapter.go
- controllers/integrationpipeline/integrationpipeline_adapter_test.go
- helpers/integration.go
- loader/loader.go
- loader/loader_mock.go
- loader/loader_mock_test.go
- loader/loader_test.go
* Currently, we are processing Intg PLRs that are already finished, are marked for deletion, and don't contain a finalizer.
* This causes a problem when a user deletes the TaskRun(s) of this PLR, and then deletes it.
* Because our service tries to reconcile it as it just got marked for deletion. And then hits this bug when we aren't able to fetch all/some of its TaskRuns.
> fix(STONEINTG-752): don't reconcile unnecessary Integration PLRs

- config/rbac/kustomization.yaml
- config/rbac/snapshotgc_rbac.yaml
- config/snapshotgc/kustomization.yaml
- config/snapshotgc/snapshotgc.yaml
Adding a cronjob and associated rbac resources for running the snapshots garbage collector
> chore(RHTAPWATCH-778): add snapshotgc cronjob

- cmd/snapshotgc/snapshotgc.go
Allow overriding the snapshots-to-keep vars with env vars.
> chore: override variables with env vars when provided

- status/reporters.go
- status/reporters_test.go
Github reporter must process also invalid status of integration test. This status has been added recently, this is missing coutner part.
> fix(STONEINTG-807): report invalid test run into GH

- controllers/snapshot/snapshot_controller_test.go
Before this commit:
* Currently, this unit test fails intermittently because it first deletes the Application and then reconciles the related Snapshot, in the hope that the controller will stop the reconciliation because of the missing App and mark the Snapshot as Invalid.
* But since, when the App gets deleted, Snapshot also gets queued for deletion. So, this introduces a race condition where we're trying to reconcile a Snapshot, that's marked for deletion, hoping it gets successfully reconciled before the deletion.
After this commit:
* Instead of deleting the App and reconciling the Snapshot, we are pointing the Snapshot to a non-existent App to replicate the same behaviour.
* This eliminates the race condition.
> fix(STONEINTG-776): [unit-test] point the Snapshot to a non-existent Application

- metrics/integration.go
- metrics/integration_test.go
> fix(stoneinteg-761): create a new metric to replace static env

- controllers/statusreport/statusreport_adapter.go
- gitops/snapshot_predicate.go
determineIfAllIntegrationTestsFinishedAndPassed must take `TestInvalid` into account and eval it as finished test
> fix(statusreport): include TestInvalid in evaluation

- controllers/statusreport/statusreport_adapter.go
- gitops/snapshot_predicate.go
This reverts commit 06e25a01eaa84ad3bf0119844f2c27da6370cfaa.
controller is not ready for this, needs fixes to handle case when snapshot doesn't have component
> fix(statusreporting): Revert predicate creation event

- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
- controllers/statusreport/statusreport_adapter.go
- helpers/integration.go
- helpers/integration_test.go
Adds a backoff timer to continue reconciliation when auth fails for github status reporting. Will allow reconciliation to continue without extraneous error logging after threshold reached.
> fix(STONEINTG-751): add backoff threshold for GH authentication

- controllers/statusreport/statusreport_adapter.go
- loader/loader.go
- loader/loader_test.go
* Currently, if a Snapshot doesn't contain a component label on it, the statusreport controller doesn't handle this case and causes nil pointer error.
> fix(STONEINTG-819): teach statusreport ctrl to deal with missing label

- cmd/snapshotgc/snapshotgc.go
- cmd/snapshotgc/snapshotgc_test.go
The current implementation only took github PR event type into consideration when classifying snapshots to garbage collect. This change adds support to the equivalent labels set by gitlab.
> fix(RHTAPWATCH-847): support gitlab MR event type labels

- controllers/statusreport/statusreport_adapter.go
- controllers/statusreport/statusreport_adapter_test.go
- controllers/statusreport/statusreport_controller.go
- docs/statusreport-controller.md
- gitops/snapshot.go
- go.mod
- go.sum
- status/reporter.go
- status/reporter_github.go
- status/reporter_gitlab.go
- status/reporter_gitlab_test.go
- status/status.go
> STONEINTG-769: Add GitLab commit status updates for integration tests

- controllers/buildpipeline/buildpipeline_adapter_test.go
- controllers/integrationpipeline/integrationpipeline_adapter.go
- controllers/snapshot/snapshot_adapter.go
- controllers/statusreport/statusreport_adapter.go
- controllers/statusreport/statusreport_adapter_test.go
- gitops/snapshot.go
- gitops/snapshot_test.go
Changes as blow are made to support gitlab merge request
* remove func IsSnapshotCreatedByPACPullRequestEvent()
* add func IsSnapshotCreatedByPACPushEvent()
* add func IsSnapshotCreatedBySamePACEvent()
> fix(STONEINTG-809): add merge request when judging PR event

- controllers/statusreport/statusreport_adapter.go
- status/status.go
This is regression from https://github.com/MartinBasti/integration-service/commit/bc758969f9ec196d57002c3abe2ea130e108bcd3
Before this status has been ignored at lower level, hotfixing issue.
if PLR doesn't exist anymore, at least provide users some results withou
details, not just failing silently.
ContinueProcessing had to be removed, it would prevent unlocking
finalizers.
This is just workaround, to prevent catastrophic issues on deployments.
Future fix should be about preventing to even get to state where we are
missing PLR data.
> fix(STONEINTG-769): do not block reconciliation when report fail

- controllers/buildpipeline/buildpipeline_adapter.go
We are missing details why PLR has been stopped processing.
> fix(buildpipeline): log details about unsuccessful PLR

- helpers/errorhandlers.go
Go support to join multiple errors into tree with error.Join() function. Improve detection of IntegrationService error by searching error tree. Without this patch, it would detect IntegrationService error only if it's first in list.
> fix(errors): support joined error

- status/status.go
- status/status_test.go
Trusted App name has been deprecated, new name is konflux
(Name should be configurable, but this is for another story.)
> fix(STONEINTG-810): rename to Konflux

- controllers/buildpipeline/buildpipeline_adapter.go
- controllers/buildpipeline/buildpipeline_adapter_test.go
- loader/loader.go
- loader/loader_mock.go
- loader/loader_mock_test.go
- loader/loader_test.go
This logic were supposed to prevent accidentally create snapshot for older build, however there is a bug that not only push build PLR are considered but it also compares pull-request build PLR and false positively prevents creation of push snapshots.
Given the radical prunning of tekton PLR, this feature has small benefit but great potential for future to break things again. Thus the best is to remove it altogether.
> fix(STONEINTG-848): drop logic for detecting latest PLR

- controllers/binding/snapshotenvironmentbinding_controller.go
- controllers/snapshot/snapshot_controller.go
- controllers/statusreport/statusreport_adapter.go
- helpers/errorhandlers.go
- loader/loader.go
- loader/loader_test.go
* This commit treats the situation, where a Snapshot doesn't
contain the Component label, as unrecoverable.
* And therefore, in that case, throws 'errors.NewNotFound()'
so that `HandleLoaderError()` function doesn't requeue it,
and instead, decline reconciliation.
* The `GetComponentFromSnapshot()` can throw errors of
NotFound-type in 2 cases: When Component label is present
but Component resource is missing from cluster. And when
Component label is missing from the Snapshot.
* To make sure `HandleLoaderError()` can differentiate
between these 2 errors, it will now log the error as well
> fix(STONEINTG-819): don't retry if component label is missing

- controllers/statusreport/statusreport_adapter.go
- controllers/statusreport/statusreport_adapter_test.go
This commit adds different log messages for if the snapshot does not have any integration test scenarios.  The overall test result is still passed.
> fix(STONEINTG-820): make statusreport controller log for 0 scenarios

- controllers/snapshot/snapshot_adapter.go
These logs are not providing enough context about which scenario is affected.
> fix(logs): add missing scenario names

- controllers/buildpipeline/buildpipeline_adapter.go
- controllers/buildpipeline/buildpipeline_adapter_test.go
- gitops/snapshot.go
- gitops/snapshot_test.go
- helpers/errorhandlers.go
- helpers/errorhandlers_test.go
Don't add containerImage with invalid digest to component
> feat(STONEINTG-786): disallow invalid containerImage to be added to component

- gitops/snapshot.go
- gitops/snapshot_test.go
- status/status.go
- status/status_test.go
Having single record of updated time may lead into race condition, where some scenario updates are being skipped.
Due this, we have to keep status of updates per scenario.
> fix(STONEINTG-710): race condition in status update time

- cmd/snapshotgc/snapshotgc.go
- cmd/snapshotgc/snapshotgc_test.go
There are multiple event-types that can be associated with GitLab MRs. Instead of trying to enumerate them all, we change the logic to spot push events (either missing the event-type label or it has value of push/Push) and consider the rest PR snapshots.
> fix(RHTAPWATCH-847): some gitlab MR snapshots missed

- Makefile
kubernetes-sigs/controller-runtime#2693 broke
the content provider while doing docker-build with following issue[1]
In order to unblock the CI, we are pinning
sigs.k8s.io/controller-runtime/tools/setup-envtest at previous working commit[2]
[1]. kubernetes-sigs/controller-runtime#2720
[2]. kubernetes-sigs/controller-runtime@c7e1dc9
> chore: pin setup-envtest version at working commit to unblock content provider 

- status/format.go
- status/format_test.go
- status/status_test.go
* Fetch the console task log URL from CONSOLE_URL_TASKLOG environment variable
* Add the link to the task name on the detailed report so it redirects to task details in Konflux UI console
Example updated detailed report with task links:
> feat(STONEINTG-844): link tasks logs to task details in git reports

- controllers/scenario/scenario_adapter.go
Fixing gosec: G601 (CWE-118): Implicit memory aliasing in for loop.
> fix(gosec): implicit memory aliasing in for loop

- Dockerfile
* Add name and com.redhat.component labels
* Replace RHTAP with Konflux in each image label
> fix: overwrite missing inherited labels

- git/github/github.go
- git/github/github_test.go
- status/reporter.go
- status/reporter_github.go
- status/reporter_github_test.go
- status/status.go
- status/status_test.go
We added new field to github  endpoint CheckRun and CommitStatus on the creation : 
-  CheckRun           ->        DetailsURL
-  CommitStatus   ->        TargetURL
For more details see  [STONEINTEG-843](https://issues.redhat.com/browse/STONEINTG-843)
> feat(STONEINTG-843): add consoleURL plr to github checkrun 

- controllers/scenario/scenario_adapter.go
- controllers/scenario/scenario_adapter_test.go
- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
- gitops/snapshot.go
- gitops/snapshot_test.go
- helpers/scenario.go
- helpers/scenario_test.go
* Continue running other ITS PLR if one ITS is misconfigured or ITS PLR fails
Signed-off-by: Hongwei Liu <hongliu@gmail.com>
> feat(STONEINTG-578): don't block other ITS test if one of them fails

- config/grafana/dashboard.yaml
- config/grafana/dashboards/integration-service-health.json
- config/grafana/kustomization.yaml
The integration service health dashboard include the CPU/memory utilization percentage and the reconcilation errors per controller 
> feat(STONEINTG-872): create integration health dashboard in grafana

- gitops/snapshot.go
- status/reporter_gitlab.go
- status/reporter_gitlab_test.go
Bug: When a MR is created from the foked repo, we still try to get/create MR note from
source target project incorrectly
The fix will:
* Get source project ID from PAC annotation
pac.test.appstudio.openshift.io/source-project-id and create/get
commitStatus from it
* Get target project id from PAC annotation
pac.test.appstudio.openshift.io/target-project-id and create/update
MR note from this project
> fix(KFLUXBUGS-1202): use proper project id when talking with GL project

- controllers/statusreport/statusreport_adapter.go
- controllers/statusreport/statusreport_adapter_test.go
- docs/statusreport-controller.md
- pkg/integrationteststatus/integration_test_status.go
- pkg/integrationteststatus/integration_test_status_test.go
> feat(STONEINTG-781): remove finalizer sooner for integration plr

- status/format.go
- status/format_test.go
* Solves the error 422 Validation Failed for checkRuns because details_url must use the http or https
> fix(STONEINTG-885): add https to developmet console links

- config/grafana/dashboards/integration-service-health.json
Issue:
*There is error message in health dashboard CPU metric https://grafana-access-appstudio-grafana.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/d/b18e4904-b2c7-4942-8df6-60ffeeb04dde/integration-service-health?orgId=1&from=now-24h&to=now&inspect=7&inspectTab=error:
Status: 500. Message: execution: multiple matches for labels:
many-to-one matching must be explicit (group_left/group_right)
Fix:
* add group_left to fix  the error Errorexecuting query:multiple matchesforlabels:many-to-one matching must beexplicit(group_left/group_right). Refer to https://iximiuz.com/en/posts/prometheus-vector-matching/
> fix(STONEINTG-872) add group_left() to fix many-to-one matching issue

- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
- controllers/snapshot/snapshot_controller.go
- docs/snapshot-controller.md
- gitops/binding.go
- gitops/binding_test.go
- gitops/snapshot.go
- gitops/snapshot_test.go
To stop deploying successful snapshot to root envs, integration need to:
* Remove EnsureSnapshotEnvironmentBindingExist() and all associated (unused) functions and related unit tests
* Update controller diagram
This PR need to wait for [e2e PR](https://github.com/redhat-appstudio/e2e-tests/pull/1125) to pass integration-service-e2e
This PR might be merged after PR https://github.com/redhat-appstudio/integration-service/pull/572/files, then the shared SEB functions should be re-checked and removed.
> feat(STONEINTG-697): Stop deploying successful snapshot to root envs

- status/reporter_gitlab.go
Make some error messages in the gitlab reporter initialization correctly report "annotation" rather than "label."  Also differentiate betwen missing source project id and target project id annotations
> fix: clarify error messages in gitlab reporter initialization

- controllers/buildpipeline/buildpipeline_adapter.go
- controllers/buildpipeline/buildpipeline_adapter_test.go
- controllers/buildpipeline/buildpipeline_controller.go
- controllers/component/component_adapter.go
- controllers/component/component_adapter_test.go
- controllers/component/component_controller.go
- controllers/integrationpipeline/integrationpipeline_adapter.go
- controllers/integrationpipeline/integrationpipeline_adapter_test.go
- controllers/integrationpipeline/integrationpipeline_controller.go
- controllers/scenario/scenario_adapter.go
- controllers/scenario/scenario_adapter_test.go
- controllers/scenario/scenario_controller.go
- controllers/snapshot/snapshot_adapter.go
- controllers/snapshot/snapshot_adapter_test.go
- controllers/snapshot/snapshot_controller.go
- controllers/statusreport/statusreport_adapter.go
- controllers/statusreport/statusreport_adapter_test.go
- controllers/statusreport/statusreport_controller.go
- gitops/snapshot.go
- gitops/snapshot_integration_tests_status.go
- gitops/snapshot_integration_tests_status_test.go
- gitops/snapshot_test.go
- helpers/integration.go
- helpers/integration_test.go
- loader/loader.go
- loader/loader_mock.go
- loader/loader_mock_test.go
- loader/loader_test.go
- status/status.go
- tekton/integration_pipeline_test.go
Refactor params in a way that context is first param
> refactor(STONEINTG-774): make ctx first param

- controllers/component/component_adapter.go
- controllers/component/component_controller_test.go
- loader/loader.go
- loader/loader_mock.go
- loader/loader_mock_test.go
- loader/loader_test.go
We have been running into the issue that finalizers are being add to objects that are being deleted - components.
This changes should prevent that from happening by getting the object before such action.
> fix(STONEINTG-828): dont' add finalizer to deleted component

- Makefile
In tests we need CRDs from other projects, however go mod vendor has aggresive pruning and vendor module doesn't contain CRDs.
Thus as a workaround, we have to manually fetch some modules to have all content available in tests.
https://github.com/golang/go/issues/26366
> fix: missing CRDs due to vendoring

- api/v1alpha1/integrationtestscenario_conversion.go
- api/v1alpha1/integrationtestscenario_types.go
- config/crd/bases/appstudio.redhat.com_integrationtestscenarios.yaml
- config/crd/patches/webhook_in_integrationtestscenarios.yaml
* Convert v1alpha1 IntegrationTestScenarios to the v1beta2 version by converting bundle to resolverRef and removing Environment config
* Re-serve v1alpha1 version
> fix(STONEINTG-841): add v1alpha1 to v1beta2 conversion webhook

- internal/controller/snapshot/snapshot_adapter.go
- tekton/integration_pipeline.go
- tekton/integration_pipeline_test.go
* Integration pipelineRuns can now apply default timeouts for pipeline, task and finally based on environment variables
> fix(KFLUXBUGS-1218): add support for pipelineRun timeouts

- Dockerfile
Upgrading glibc manually because parent image doesn't contain fix yet
> fix: glibc CVE

- api/v1beta1/integrationtestscenario_conversion.go
* The conversion was copying the empty destination resolver
info instead of the source data
> fix(STONEINTG-928): conversion of v1beta1 params

- Dockerfile
Parent image has been updated and fixed, we don't need manual update of glibc anymore
This reverts commit d37052025c5e8a3f9c634a8fc6d46082d6c88b85.
> Revert "fix: glibc CVE"

- internal/controller/statusreport/statusreport_adapter.go
* The previous way of logging is causing a panic:
```
{"level":"dpanic","ts":"2024-05-16T04:28:59Z","logger":"controllers.statusreport","caller":"statusreport/statusreport_adapter.go:134","msg":"odd number of arguments passed as key-value pairs for logging","snapshot":{"name":"integ-app-xuce-hdngm","namespace":"stat-rep-kxmp-tenant"},"application":"stat-rep-kxmp-tenant/integ-app-xuce","ignored key":2,"stacktrace":"github.com/konflux-ci/integration-service/internal/controller/statusreport.(*Adapter).EnsureSnapshotFinishedAllTests
```
as seen in [our controller logs](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests-periodic/1790955678383214592/artifacts/appstudio-e2e-tests-periodic/gathe …
> chore: fix panic due to incorrect logging

- .github/workflows/codecov.yml
- .github/workflows/pr.yaml
- Dockerfile
- go.mod
- go.sum
Bumping required version of go to 1.21
> feat(STONEINTG-893): use go 1.21

- internal/controller/snapshot/snapshot_adapter.go
- internal/controller/snapshot/snapshot_adapter_test.go
* This commit now ensures that all the errors that occur while Integration PLR creation, are logged into the Snapshot's status annotation.
* Earlier only Invalid-type errors were logged, leaving behind other types of error from the annotation.
* This made it difficult for users to understand what went wrong, because annotation was, in some cases, stuck on "Pending" status.
> feat(STONEINTG-849): write all Integration-PLR-creation errors to snapshot annotation

- config/rbac/role.yaml
- internal/controller/snapshot/snapshot_controller.go
* As part of KFLUXBUGS-1290, the component webhooks now add owner references to updated CRs. Because of this any entity that updates components needs to have delete permissions for them
> fix(KFLUXBUGS-1299): add delete permissions for components

- tekton/integration_pipeline_test.go
[STONEBLD-2339](https://issues.redhat.com//browse/STONEBLD-2339)
The build-definitions repo has moved from github.com/redhat-appstudio to
github.com/konflux-ci. Update references accordingly.
Signed-off-by: Adam Cmiel <acmiel@redhat.com>
> chore: update build-definitions references to new org

- internal/controller/snapshot/snapshot_adapter.go
Goal is to prevent reconcialtion being in infinite look retrying to create pipelinerun. We will catch this specific action when the webhook validation failed and report test status as invalid.
> fix(STONE-876): catch admission validation error

- docs/snapshot-controller.md
- internal/controller/snapshot/snapshot_adapter.go
- internal/controller/snapshot/snapshot_adapter_test.go
* Update global component list once the push snapshot is created for component, don't wait for the successful integration test any more
> feat(STONEINTG-881): update GCL once push snapshot is created for component

- docs/integration_pipeline_controller.md
- docs/scenario-controller.md
- helpers/integration.go
- helpers/integration_test.go
- internal/controller/integrationpipeline/integrationpipeline_adapter.go
- internal/controller/integrationpipeline/integrationpipeline_adapter_test.go
- internal/controller/integrationpipeline/integrationpipeline_controller.go
- internal/controller/scenario/scenario_adapter.go
- internal/controller/scenario/scenario_adapter_test.go
- internal/controller/scenario/scenario_controller.go
Remove code associated with EnsureEphemeralEnvironmentsCleanedUp().
- Remove EnsureEphemeralEnvironmentsCleanedUp()to stop cleanup ephemeral environment
- Stop adding finalizers to IntegrationTestScenarios
- Remove the related functions and related unittests
- Update all related documentation, diagram
> fix(STONEINTG-815): remove ephemeral env cleanup code

- Dockerfile
Upgrading glibc manually because parent image doesn't contain fix yet
> fix: update glibc because of CVE

- status/status.go
- status/status_test.go
* get Konflux console name from environment variable
> fix(STONEINTG-861): get Konflux console name from env

- status/status.go
* We're logging the value of the struct to help
us with debugging in case of race conditions.
* We'll be requeueing in case we hit an error
while updating the "git-reporter-status" anntn
* This will log silent errors, and help us debug.
> chore(STONEINTG-938): Improve error reporting and log annotation value for better debuggability

- gitops/snapshot.go
- gitops/snapshot_test.go
- internal/controller/snapshot/snapshot_adapter.go
- internal/controller/snapshot/snapshot_adapter_test.go
- tekton/integration_pipeline.go
> Run integration test from pr

- api/v1beta2/integrationtestscenario_webhook.go
- api/v1beta2/integrationtestscenario_webhook_test.go
Add additonal webhook validation added to ITS to prevent creation of ITS with the snapshot param set manually.
> feat(STONINTG-896): prevent creation of ITS with snapshot set manually

- internal/controller/snapshot/snapshot_adapter.go
- internal/controller/snapshot/snapshot_adapter_test.go
- internal/controller/snapshot/snapshot_controller.go
- tekton/integration_pipeline.go
- tekton/integration_pipeline_test.go
* Remove "component" from the Snapshot adapter and try to retreive it only when updating the Global Candidate List
* Update the integration pipeline creation logic to only copy the component label from the Snapshot and not require the component CR
> feat(STONEINTG-882): make component optional in snapshot controllers

- Dockerfile
* The updated ubi image should have the correct version of glibc without problematic vulnerabilities, so no need to update it separately
> fix: revert glibc upgrade

- docs/snapshot-controller.md
- gitops/snapshot.go
- gitops/snapshot_test.go
- internal/controller/snapshot/snapshot_adapter.go
- internal/controller/snapshot/snapshot_adapter_test.go
* introduce a new type of snapshot: override
* update global candidate list if a override snapshot contains the component with valid digest
> feat(STONEINTG-892): support new override snapshot

- gitops/snapshot.go
- gitops/snapshot_test.go
* Don't return an error when constructing a Snapshot in case one of the existing (non-built) components has an invalid image reference in their GCL (spec.containerImage)
* Do return an error in case the newly built image is invalid
> fix(KFLUXBUGS-1355): skip components with invalid images

- internal/controller/snapshot/snapshot_adapter.go
- internal/controller/snapshot/snapshot_adapter_test.go
* When promoting components from an override Snapshot, update the component source revision if available
> fix: update component source revision during override

- helpers/integration.go
- status/format.go
- status/format_test.go
This PR prevents reporting empty string to webUI when PLR finishes. In case that TEST_OUTPUT is nil, we check status conditions for given taskrun and report it.
> fix(STONEINTG-960): show conditions in webUI

- .github/dependabot.yml
* Add chipspeak (Patrick O'Connor) to team members configuration
> chore(STONEINTG-972): update integration team members

- docs/statusreport-controller.md
- gitops/snapshot.go
- internal/controller/buildpipeline/buildpipeline_adapter.go
- internal/controller/buildpipeline/buildpipeline_adapter_test.go
- internal/controller/component/component_adapter.go
- internal/controller/statusreport/statusreport_adapter.go
- internal/controller/statusreport/statusreport_adapter_test.go
I've been a little vicious about composite snapshot code removal.
Updated diagram containing composite snapshot also.
Feel free to address what needs to remain.
> feat(STONEINTG-961): remove composite snapshot

- gitops/snapshot.go
- internal/controller/buildpipeline/buildpipeline_adapter.go
- internal/controller/buildpipeline/buildpipeline_adapter_test.go
- internal/controller/snapshot/snapshot_adapter.go
- internal/controller/snapshot/snapshot_adapter_test.go
- tekton/integration_pipeline.go
- tekton/integration_pipeline_test.go
* Copy custom.appstudio.openshift.io prefixed labels and annotations from build pipelineRuns to Snapshots
* Copy all labels and annotations prefixed with test.appstudio.openshift.io/ and custom.appstudio.openshift.io/ from the Snapshot to integration pipelineRuns
Example labels in a build pipelineRun (reduced for readability):
Example Snapshot's labels created for that build pipelineRun:
Example of the copied labels in the integration pipelineRun:
> feat(STONEINTG-953): copy test and custom labels/annotations

- config/grafana/dashboards/integration-service-dashboard.json
- internal/controller/buildpipeline/buildpipeline_adapter.go
- internal/controller/component/component_adapter.go
- pkg/metrics/integration.go
- pkg/metrics/integration_test.go
* removed the snapshot concurrent attempts metric and references within adapters and updated test file accordingly.
* adjusted panel positions and fixed inconsistent height and x/y positioning.
One test has had to be changed as it couldn't be entirely removed wholesale without breaking tests and I'm not sure why.
(see It("registers the pipeline run start time'.", func())
Note: This drops code coverage in tests by 2% but this is expected
> fix(STONEINTG-863): removed bugged snapshot concurrent requests metric

- .tekton/integration-service-pull-request.yaml
- .tekton/integration-service-push.yaml
* Migration to the 0.2 version of the buildah task requires removing the BASE_IMAGES_DIGESTS result since it will stop being emitted
* See [migration](https://togithub.com/redhat-appstudio/build-definitions/blob/main/task/buildah/0.2/MIGRATION.md) instructions for more details
> chore: remove BASE_IMAGES_DIGESTS from konflux pipelines

- .github/CODEOWNERS
- .github/dependabot.yml
> chore(STONEINTG-888): added CODEOWNERS

- docs/snapshot-controller.md
- gitops/snapshot.go
- gitops/snapshot_test.go
- internal/controller/snapshot/snapshot_adapter.go
- internal/controller/statusreport/statusreport_adapter.go
* Integration service uses the contexts field to decide when to use IntegrationTestScenarios for the given Snapshot
* The new filtering function is applied whenever a list of scenarios is fetched to decide which pipeline to run or when deciding if all required integration test scenarios finished
> feat(STONEINTG-974): filter Scenarios based on Snapshot context

- docs/build_pipeline_controller.md
- gitops/snapshot.go
- internal/controller/buildpipeline/buildpipeline_adapter.go
- internal/controller/buildpipeline/buildpipeline_adapter_test.go
- internal/controller/buildpipeline/buildpipeline_controller.go
- tekton/build_pipeline.go
- tekton/build_pipeline_test.go
1. Add EnsurePRGroupAnnotated() to build pipelineRun adapter and save build source branch info to build PLR metadata as below
* save pr group to annotation test.appstudio.openshift.io/pr-group
* save pr group in hash format to label test.appstudio.openshift.io/pr-group-sha
2.Save build PLR start time to snapshot annotation test.appstudio.openshift.io/pipelinerunstarttime
> feat(STONEINTG-997): save build PLR info to build PLR and snapshot metadata

- Dockerfile
> chore(STONEINTG-989): update image to ubi9

- internal/controller/buildpipeline/buildpipeline_adapter.go
- internal/controller/buildpipeline/buildpipeline_adapter_test.go
- tekton/build_pipeline.go
- tekton/build_pipeline_test.go
* annotate/label pr group info for pr PLR only
> feat(STONEINTG-997): annotate pr group for pr PLR only

- internal/controller/buildpipeline/buildpipeline_adapter.go
- internal/controller/buildpipeline/buildpipeline_adapter_test.go
stop reconciliation when creating snapshot meets invalid image digest error
> fix(stoneintg-971): reconciliation invalid image digest err

- gitops/snapshot.go
- internal/controller/snapshot/snapshot_adapter.go
- internal/controller/snapshot/snapshot_adapter_test.go
Integration Service was overwriting the revision sha of the integration test scenarios targeting a specific sha with the sha of the source branch. In situations where the source branch sha differs from the ITS within the PR, the sha from the target branch will be used to create the PLR.
> fix(STONEINTG-980): consider target branch when overwriting ITS

- .tekton/integration-service-pull-request.yaml
- .tekton/integration-service-push.yaml
* The sbom-json-check task is deprecated and will start failing the EC checks if it's not removed
> chore: remove sbom-json-check task from build pipelines

- docs/snapshot-controller.md
- git/github/github.go
- git/github/github_test.go
- gitops/snapshot.go
- gitops/snapshot_test.go
- internal/controller/buildpipeline/buildpipeline_adapter.go
- internal/controller/snapshot/snapshot_adapter.go
- internal/controller/snapshot/snapshot_adapter_test.go
- internal/controller/snapshot/snapshot_controller.go
- loader/loader.go
- loader/loader_mock.go
- loader/loader_mock_test.go
- loader/loader_test.go
- status/mock_status.go
- status/reporter_github.go
- status/reporter_github_test.go
- status/status.go
- tekton/build_pipeline.go
- tekton/build_pipeline_test.go
* Create group snapshot for the component snapshots with opened PR and  belonging to the same pr group once a component snasphot is created for PR
* Set group to snapshot type to group snapshot
* Set event-type to pull-request to group snapshot
* Set pr-group annotation and pr-group-sha label from component snasphot to group snapshot
> feat(STONEINTG-998): support group snapshot

- status/status.go
Coming from [slack thread](https://redhat-internal.slack.com/archives/C030SGP2VB9/p1725365370664139) and https://github.com/konflux-ci/e2e-tests/pull/1363/checks?check_run_id=29611513385
Add pipelineRun name to details then we can have a chance to debug it next time
> fix: improve details message for notfound PLR in status report

- gitops/snapshot.go
- gitops/snapshot_predicate_test.go
- gitops/snapshot_test.go
- internal/controller/buildpipeline/buildpipeline_adapter_test.go
- internal/controller/integrationpipeline/integrationpipeline_adapter_test.go
- internal/controller/snapshot/snapshot_adapter_test.go
- internal/controller/statusreport/statusreport_adapter_test.go
- loader/loader_test.go
- tekton/build_pipeline.go
- tekton/build_pipeline_test.go
* fix IsSnapshotCreatedByPACPushEvent and IsPLRCreatedByPACPushEvent since incoming event can trigger pull-request and push event plr
> fix(STONEINTG-998): fix pipeline as code event

- config/grafana/dashboards/integration-service-dashboard.json
add two availability panels for I.S. service
one to measure uptime and one to measure violations
> chore(stoneintg-1023): add IS SLO availability panels

- integration-tests/pipelines/konflux-e2e-tests.yaml
> feat(KONFLUX-3903): create pipeline to run tests in konflux

- gitops/snapshot.go
* don't release group snapshot since it is created for PR/MR
* label group snapshot with pr-group-sha
> fix(STONEINTG-998): don't release group snapshot

- config/grafana/dashboards/integration-service-dashboard.json
change the availability SLO for integration service to average over a 24 hr period instead of 1 hr
> chore(stoneintg-1023): change availability SLO to 24 hrs agg

- tekton/predicates.go
* It's not guaranteed that a failed build pipelineRun will be processed by Tekton chains
* The integration service still needs to process those pipelineRuns in order to remove their finalizers
> fix(STONEINTG-897): don't require chains for failed build PLRs

- integration-tests/pipelines/konflux-e2e-tests.yaml
> feat: Remove test-metadata test-event-type and use integration service contexts

- docs/statusreport-controller.md
- gitops/snapshot.go
- gitops/snapshot_test.go
- internal/controller/statusreport/statusreport_adapter.go
- internal/controller/statusreport/statusreport_adapter_test.go
- status/format.go
- status/format_test.go
- status/mock_status.go
- status/reporter_github.go
- status/status.go
- status/status_test.go
* update template to generate text reported to git provider
* report test status for group snapshot
> feat(STONEINTG-999): report test status for group snapshot

- git/github/github.go
- internal/controller/snapshot/snapshot_adapter.go
When gitlab/github repo is deleted group snapshot creation fails while attempting to get the pr status from the repo.
> fix(STONEINTG-1048): stop reconciliation when failing to get pr status

- gitops/snapshot.go
- gitops/snapshot_test.go
- internal/controller/snapshot/snapshot_adapter.go
- internal/controller/statusreport/statusreport_adapter_test.go
- status/format.go
- status/format_test.go
* Extend group test info in group snapshot to include repourl and pr
> feat(STONEINTG-1033): extend group test info fields

- status/format.go
* a fix for format in status report
> fix(STONEINTG-1033): fix for format in status report

- internal/controller/snapshot/snapshot_adapter.go
- internal/controller/snapshot/snapshot_adapter_test.go
Reverts konflux-ci/integration-service#901
There's a bug in our code from a previous commit that means `status.lastUpdatedImage` isn't being updated for all snapshots.  We can't remove `spec.containerImage` until that's fixed.
> Revert "chore(stoneintg-1008): stop referencing/updating spec.containerImage"

- git/github/github.go
- helpers/errorhandlers.go
- helpers/errorhandlers_test.go
- internal/controller/snapshot/snapshot_adapter.go
- internal/controller/snapshot/snapshot_adapter_test.go
- status/reporter.go
- status/reporter_github.go
- status/reporter_github_test.go
- status/reporter_gitlab.go
- status/status.go
- status/status_test.go
* stop reconciliation for unrecoverable error when getting PR/MR status during group snapshot preparation
> fix(STONEINTG-1048): stop reconciliation for unrecoverable error during group snapshot creation

- .tekton/integration-service-pull-request.yaml
- .tekton/integration-service-push.yaml
* adding rpms-signature-scan task to build pipeline to pass EC check, refer to the failure in EC check https://github.com/konflux-ci/integration-service/pull/910 and push pipelinerun in PR https://github.com/konflux-ci/integration-service/pull/915 https://console.redhat.com/application-pipeline/workspaces/rhtap-integration/applications/integration-service/pipelineruns/integration-service-enterprise-contract-6dhmc/logs
```
"violations": [
{
"msg": "Required task \"rpms-signature-scan\" is missing",
"metadata": {
"code": "tasks.required_tasks_found",
"collections": [
"redhat"
],
"depends_on": [
"tasks.pipeline_has_tasks"
],
"description": "Ensure that the set of required tasks are included in the PipelineRun attestation. To exclude this rule add …
```
> fix: add rpms-signature-scan task to pipelines

- internal/controller/snapshot/snapshot_adapter.go
- internal/controller/snapshot/snapshot_adapter_test.go
- internal/controller/statusreport/statusreport_adapter.go
- internal/controller/statusreport/statusreport_adapter_test.go
- loader/loader.go
- loader/loader_mock.go
- loader/loader_mock_test.go
- loader/loader_test.go
Reduce the complexity to 13(Checking by `gocyclo .`)
> chore(STONEINTG-824) reduce complexity in statusreport adapter

- config/grafana/dashboards/integration-service-health.json
- internal/controller/buildpipeline/buildpipeline_controller.go
- internal/controller/integrationpipeline/integrationpipeline_controller.go
Prior to this change the grafana dashboard for integration service errors showed the errors for both the build and integration pipeline controllers together.  This change separates them for clearer debugging
> chore(stoneintg-1079): separate build and test pipeline failures

- config/grafana/dashboards/integration-service-health.json
> fix: duplicate refID in grafana panel

- gitops/snapshot.go
- gitops/snapshot_test.go
- go.mod
- internal/controller/snapshot/snapshot_adapter.go
- internal/controller/snapshot/snapshot_adapter_test.go
- loader/loader.go
- loader/loader_mock.go
- loader/loader_mock_test.go
- loader/loader_test.go
* don't check the snapshots which are not affected by pr group during group snapshot preparation
> feat(STONEINTG-1071): skip checking snapshot not affected by pr group

- internal/controller/integrationpipeline/integrationpipeline_adapter.go
- internal/controller/statusreport/statusreport_adapter.go
- status/reporter_github.go
- status/reporter_github_test.go
- status/reporter_gitlab.go
- status/reporter_gitlab_test.go
> feat(STONEINTG-851): allow status reports on push events

- internal/controller/buildpipeline/buildpipeline_adapter.go
If a build pipeline in a PR group fails before other PRs in the same group we attempt to notify snapshots that have already been created.
This change fixes a bug in which the service would panic and crash if not snapshots had been created for that PR group
> fix: group snapshot error causing panic

- internal/controller/buildpipeline/buildpipeline_adapter.go
> fix(STONEINTG-1086): annotate build PLR when failing to create snapshot

- internal/controller/snapshot/snapshot_adapter.go
- internal/controller/snapshot/snapshot_adapter_test.go
- loader/loader.go
- loader/loader_mock.go
- loader/loader_mock_test.go
- loader/loader_test.go
* Before this commit, a user can only rerun one test at a time by adding the "run" label on snapshot with the name of ITS they want to rerun.
* After this commit, a user can add the value of "all" in the "run" label of snapshot to automatically rerun ALL the tests easily.
> feat(STONEINTG-1065): let users rerun ALL tests

- docs/statusreport-controller.md
- gitops/snapshot.go
- gitops/snapshot_test.go
- internal/controller/buildpipeline/buildpipeline_adapter_test.go
- status/reporter_github.go
- status/reporter_github_test.go
- status/reporter_gitlab.go
- status/reporter_gitlab_test.go
* Don't set commitStatus if the PR/MR is from forked repo since the limitation access
> fix(STONEINTG-1091): don't set commitStatus for PR/MR from forked repo

- gitops/snapshot.go
- internal/controller/component/component_adapter.go
- internal/controller/snapshot/snapshot_adapter.go
Attempt to use status.lastPrommotedImage as the source of truth for the gcl.  Fall back on the spec.containerImage field, despite the fact that it may have been changed by imageRepository
> feat: begin referencing status.lastPromotedImage

- Makefile
- config/manager/kustomization.yaml
- config/snapshotgc/snapshotgc.yaml
- docs/pull_request_template.md
> chore(STONEINTG-949): migrate service image to konflux-ci

- api/v1beta2/integrationtestscenario_types.go
- internal/controller/snapshot/snapshot_adapter.go
- tekton/integration_pipeline.go
- tekton/integration_pipeline_test.go
* If the ITS has any of the following annotations: 
* test.appstudio.openshift.io/pipeline_timeout 
* test.appstudio.openshift.io/tasks_timeout 
* test.appstudio.openshift.io/finally_timeout
* Use them to overwrite the default timeouts that are set in configmaps
> feat(KFLUXBUGS-1889): set ITS timeouts from annotations

- internal/controller/snapshot/snapshot_adapter.go
- internal/controller/snapshot/snapshot_adapter_test.go
- internal/controller/snapshot/snapshot_controller.go
- internal/controller/snapshot/snapshot_controller_test.go
> feat(STONEINTG-883): Set owner reference to application for ALL Snapshots

- gitops/snapshot.go
- gitops/snapshot_test.go
fix func IsSnapshotCreatedByPACPushEvent for group snapshot
> fix(STONEINTG-1110): fix for IsSnapshotCreatedByPACPushEvent

- tekton/integration_pipeline.go
- tekton/integration_pipeline_test.go
* If the sum of tasks and finally timeout durations is greater than the pipeline timeout duration, set the pipeline timeout to that sum in order to prevent a pipelineRun validation failure
> fix(KONFLUX-5949): prevent pipelineRun timeout validation failures

- docs/build_pipeline_controller.md
- gitops/snapshot.go
- helpers/build.go
- internal/controller/buildpipeline/buildpipeline_adapter.go
- internal/controller/buildpipeline/buildpipeline_adapter_test.go
- internal/controller/buildpipeline/buildpipeline_controller.go
- internal/controller/snapshot/snapshot_adapter.go
- internal/controller/snapshot/snapshot_adapter_test.go
- internal/controller/statusreport/statusreport_adapter.go
- pkg/integrationteststatus/integration_test_status.go
- pkg/integrationteststatus/integrationteststatus_enumer.go
- status/reporter_github.go
- status/reporter_gitlab.go
- status/status.go
- status/status_test.go
* set integration tests status to pending when build plr is triggered or retriggered
* set integration test status to failed/cancelled when build plr fails
* set integration test status to failed/cancelled with failure reason when snapshot is not created to show to users on git provider
Signed-off-by: Hongwei Liu<hongliu@redhat.com>
>  feat(KONFLUX-5971): set intg test status in git according to PR bld PLR

- internal/controller/integrationpipeline/integrationpipeline_adapter.go
- internal/controller/integrationpipeline/integrationpipeline_adapter_test.go
- internal/controller/statusreport/statusreport_adapter.go
- internal/controller/statusreport/statusreport_adapter_test.go
* update the initial condition in the EnsureSnapshotTestStatusReportedToGitProvider function to only process component and group snapshots
* Remove the finalizer from Integration PLRs if the snapshot is not group or component type and its PLR has finished or has been deleted
> fix(STONEINTG-1100): don't report status for manual Snapshots

- internal/controller/statusreport/statusreport_adapter.go
* remove pr name from integration test report in checkRun and commitStatus
> fix(STONEINTG-1096): remove pr name from integration test report title

- gitops/snapshot.go
- internal/controller/snapshot/snapshot_adapter.go
- release/releaseplan.go
- release/releaseplan_test.go
* This is useful for a developer who has enabled auto-releases for their Application.
* They will now have a deterministic way to find the Release related to a particular code change
* They can search Release CR with the short SHA value (first 7 chars) belonging to their commit
* This will make it easy for them to relate a Release with a code change.
> feat(STONEINTG-1068): add SHA value in Release CR name

- internal/controller/statusreport/statusreport_adapter.go
* log error when status report fails for completed
integration plr
* this is not a fix, but it can help to debug why finalizer is not
removed from integration PLR that causes intg plr can't be pruned
> feat(STONEINTG-1123): log error when failing to report status for completed integration pipelinerun

- api/v1beta2/integrationtestscenario_types_test.go
- api/v1beta2/integrationtestscenario_webhook.go
- api/v1beta2/integrationtestscenario_webhook_test.go
No validation is done on the git resolver in the ITS, which can lead to errors when users attempt to run the tests.  This change adds basic validation to the ITS admission controller to verify that no fields contain leading or trailing whitespace and that URLs and secret names, if provided, are syntactically valid.
> fix(stoneintg-1017): validate git resolver in integration test scenario

- .tekton/integration-service-push.yaml
Seems like if not using same tasks version to build pristine and sealights image is broking enterprise contract:
```
✕ [Violation] trusted_task.trusted
ImageRef: quay.io/redhat-user-workloads/rhtap-integration-tenant/integration-service/integration-service@sha256:e1d230c8de65be3e5a8d0aac8390341fd71522d8a3ab8c7f7d66c79734e52209
Reason: Code tampering detected, untrusted PipelineTask "build-sealights-container" (Task "buildah-oci-ta") was included in
build chain comprised of: build-sealights-container, clone-repository, prefetch-dependencies, sealights-go-instrumentation
Title: Tasks are trusted
Description: Check the trust of the Tekton Tasks used in the build Pipeline. There are two modes in which trust is verified. The
first mode is used if Trusted Artifacts are enabled. In this case, a …
```
> fix: use same tekton task version to build pristine image and sealights images in push events

- gitops/snapshot_predicate.go
- gitops/snapshot_predicate_test.go
- tekton/predicates.go
- tekton/predicates_test.go
* Modify the integrationpipeline controller to react to 'create' events in order to handle finished integration PLRs in case their events were missed.
* Modify statusreport controller to react to 'create' events in order to handle Snapshots with updated status annotation in case their events were missed
* Create events are triggered upon service re-sync, either every 10hrs or every restart
* This allows us to record/report the status in the Snapshot and remove the PLR finalizers, as well as to report the missed events
> fix(KONFLUX-5832): resync missed integration PLRs

- cmd/snapshotgc/snapshotgc.go
- cmd/snapshotgc/snapshotgc_test.go
* Since the new Konflux clusters do not use toolchain to provision user tenant namespaces, we need to use a new way to identify them: via the `konflux.ci/type` label
> fix(STONEINTG-1136): garbage collector checks konflux user namespaces

- .github/workflows/codecov.yml
- .github/workflows/pr.yaml
The ubuntu-20.04 image for github actions is being deprecated. Workflows that still rely on the image after April 1, 2025 willl no longer work. We need to update to ubuntu-24.04 to avoid this.
> chore(stoneintg-1134): update github workflows to ubuntu-24.04

- .github/CODEOWNERS
> chore: remove Pat from integration-service's CODEOWNERS

- gitops/snapshot.go
- helpers/integration.go
- internal/controller/snapshot/snapshot_adapter.go
- internal/controller/snapshot/snapshot_adapter_test.go
- loader/loader.go
- loader/loader_mock.go
This is currently WIP, need to add unit tests for coverity. Reviews/feedback in a meantime are most welcome.
> feat(STONEINTG-1050): cancel old intg pipelineruns

- integration-tests/pipelines/konflux-e2e-tests.yaml
> feat(): use always sealights images for testing purpose

- .tekton/integration-service-pull-request.yaml
- .tekton/integration-service-push.yaml
* Add the sast-shell-check-oci-ta and sast-unicode-check-oci-ta tasks to the integration service build pipelineRun defintions
* The new SAST check tasks will be required by Conforma policies starting next month
> feat(STONEINTG-1135): add unicode and shell check tasks

- status/reporter_github.go
- status/reporter_github_test.go
* get secret and private key name used pipelines as code from integration service config
* use default value if they can not be found
> feat(STONEINTG-569): get pac secret and private key name from config

- .tekton/integration-service-pull-request.yaml
- .tekton/integration-service-push.yaml
https://issues.redhat.com/browse/KFLUXDP-180
* adding a new parameter to the Sealights instrumentation task to skip saving the token in TA - that way it is safe to push the image to public repository
> fix: do not store SL token

- gitops/snapshot.go
- gitops/snapshot_test.go
- internal/controller/buildpipeline/buildpipeline_adapter.go
- internal/controller/buildpipeline/buildpipeline_adapter_test.go
- internal/controller/snapshot/snapshot_adapter.go
- internal/controller/snapshot/snapshot_adapter_test.go
- internal/controller/statusreport/statusreport_adapter.go
- loader/loader.go
- loader/loader_mock.go
- loader/loader_mock_test.go
- loader/loader_test.go
- status/mock_status.go
- status/status.go
- status/status_test.go
- tekton/build_pipeline.go
- tekton/build_pipeline_test.go
* set intg status to pending for group context ITS if group snapshot is expected
* get builds PLR and snapshots for the pr group in build PLR to check if multiple component is affected by the same pr group
> feat(STONEINTG-1131): initialize pending intg status for group ITS

- internal/controller/buildpipeline/buildpipeline_adapter.go
* void nill pointer when returned ITS is nil
> fix(STONEINTG-1131): fix for nil returned ITS

- gitops/snapshot.go
- gitops/snapshot_test.go
- internal/controller/snapshot/snapshot_adapter_test.go
* fix sortSnapshot when snapshot has no annotation test.appstudio.openshift.io/pipelinerunstarttime and sort according to their creation time
> fix(STONEINTG-1141): fix sortSnapshot for group snapshot

- integration-tests/pipelines/konflux-e2e-tests.yaml
The pull Request activate the ginkgo plugin that will upload e2e tests to Sealights dashboard and get coverage + in the future will allow to enable test selections to only run tests based on code changes
> feat(): enable Sealights plugin for integration service

- internal/controller/buildpipeline/buildpipeline_adapter.go
- internal/controller/snapshot/snapshot_adapter.go
- loader/loader.go
- loader/loader_mock.go
- loader/loader_mock_test.go
- loader/loader_test.go
* Sometimes, integration test is initialized for unexpected pr group
> fix(STONEINTG-1174): fix for unexpected pr group status report

- internal/controller/buildpipeline/buildpipeline_adapter.go
- internal/controller/snapshot/snapshot_adapter.go
- internal/controller/snapshot/snapshot_adapter_test.go
- loader/loader.go
- loader/loader_mock.go
- loader/loader_mock_test.go
- loader/loader_test.go
* Should have application label when getting resources in loader
> fix(STONEINTG-1174):apply application label when getting resources

- gitops/snapshot.go
- internal/controller/snapshot/snapshot_adapter.go
the annotation helps track PipelineRuns that were stopped before completion, enabling better auditability and observability.
> feat(): add pac.test.appstudio.openshift.io/cancelled annotation to 

- api/v1beta2/integrationtestscenario_types.go
- config/crd/bases/appstudio.redhat.com_integrationtestscenarios.yaml
> feat(STONEINTG-1164): add ResolverType to ITS api

- docs/statusreport-controller.md
- gitops/snapshot.go
- gitops/snapshot_predicate_test.go
- gitops/snapshot_test.go
- internal/controller/buildpipeline/buildpipeline_adapter.go
- internal/controller/snapshot/snapshot_adapter.go
- internal/controller/statusreport/statusreport_adapter.go
- internal/controller/statusreport/statusreport_adapter_test.go
- internal/controller/statusreport/statusreport_controller.go
- internal/controller/statusreport/statusreport_controller_test.go
- pkg/integrationteststatus/integration_test_status.go
- pkg/integrationteststatus/integrationteststatus_enumer.go
- status/reporter_github.go
- status/reporter_github_test.go
- status/reporter_gitlab.go
- status/reporter_gitlab_test.go
- status/status.go
- status/status_test.go
* report group snapshot creation failure back to PRs/MRs expected to be included in group snapshot
> feat(STONEINTG-1144): report group snapshot creation failure to git provider

- cmd/snapshotgc/snapshotgc.go
- cmd/snapshotgc/snapshotgc_test.go
* The `konflux.ci/type` label was replaced with `konflux-ci.dev/type` on the newest Konflux clusters, so we need to update our garbage collector logic to take it into account
* We'll keep support for old labels to keep backwards-compatibility
> fix(ASC-783): support new label for konflux tenant namespaces

- config/default/manager_metrics_patch.yaml
- config/default/metrics_service.yaml
- config/prometheus/monitor.yaml
target endpoint is missing from observe-monitor of deployments
Signed-off-by: Kasem Alem <kalem@redhat.com>
> fix(STONEINTG-1186): fix target of IS is missing

- api/v1beta2/integrationtestscenario_types.go
- config/crd/bases/appstudio.redhat.com_integrationtestscenarios.yaml
Change Scenario.Spec.ResolverRef.ResolverType field name to ResourceKind in order to improve user clarity
> fix: change ResolverType field to ResouceKind

- git/github/github.go
- internal/controller/snapshot/snapshot_adapter.go
> fix(KFLUXSPRT-2829): show latest integration plr in github UI

- gitops/snapshot.go
- gitops/snapshot_test.go
* Canceled status of snapshot should be considered as finished when it is being checked and marked as finished in EnsureSnapshotFinishedAllTests of statusreport adapter
> fix: canceled status of snapshot should be considered as finished

- helpers/scenario.go
- helpers/scenario_test.go
* If the ITS hasn't yet been validated, the snapshot adapter will run into a nil-pointer error when fetching all scenarios and checking if that scenario is valid
* This fixes the issue by also checking if the status condition for the ITS is set in the first place
> fix: prevent nil-pointer error when ITS status isn't set

- .gitlint
Ignore all `*red-hat-konflux*` bot accounts for gitlint rules to include more than the base bot.
> fix: update gitlint ignore author

- integration-tests/pipelines/konflux-e2e-tests.yaml
Add a Task to the finally section that will wait for all other tasks to complete and then store their status in a json and uploads it to OCI artifact
[KFLUXDP-241](https://issues.redhat.com//browse/KFLUXDP-241)
in [this PR](https://github.com/konflux-ci/e2e-tests/pull/1589/files)
> feat: store pipeline status in oci artifact

- dist/chart/templates/webhook/webhooks.yaml
Fixing a bug in prod, roll back once fixed
> hotfix: ignore admission webhooks for integrationtestscenarios

- config/rbac/integrationtestscenario_admin_role.yaml
- dist/chart/templates/rbac/integrationtestscenario_admin_role.yaml
> fix: give integrationservice admins all persmissions on scenario/status

- internal/controller/snapshot/snapshot_adapter.go
When a snapshot is created, we go through the list of scenarios associated with that snapshot's application and create pipelineruns for any valid scenarios.  If a scenario is created at the same time as the snapshot then it may not be marked as valid in time for it to be run. Since the scenario is marked as neither valid nor invalid we were running into a nil point dereference from the missing status condition. This commit handles that edge case.
> fix: race condition in pipelinerun creation

- internal/controller/integrationpipeline/integrationpipeline_adapter.go
- show the PLR url to users when in progress
- otherwise, users have to copy the name and then manually goto Konflux UI and filter for the PLR
> fix: show plr url to user in check

- tekton/integration_pipeline.go
Prior to this commit the ITS spec.resolverRef.resourceKind field had to be all lowercase.  This change makes it case insensitive in order to prevent confusion from users that prefer camel case
> fix: make resourceKind case-insensitive

- integration-tests/pipelines/konflux-e2e-tests.yaml
We dont need anymore to push artifacts to quality dashboard. The dashboard is able to pull the artifacts automatically after implementing https://issues.redhat.com/browse/KFLUXDP-240
> feat(KFLUXDP-239): remove quality dashboard task

- internal/controller/integrationpipeline/integrationpipeline_adapter_test.go
* add timeout to test for EnsureIntegrationPipelineRunLogURL because time is not enought to check plr
> chore: enlarge timeout for the test EnsureIntegrationPipelineRunLogURL

- config/snapshotgc/snapshotgc.yaml
- dist/chart/values.yaml
> fix(STONEINTG-1248) adjust non-pr-snapshots count for gc

- git/github/github.go
- git/github/github_test.go
- internal/controller/buildpipeline/buildpipeline_adapter.go
- internal/controller/buildpipeline/buildpipeline_adapter_test.go
- internal/controller/snapshot/snapshot_adapter.go
- internal/controller/snapshot/snapshot_adapter_test.go
- internal/controller/statusreport/statusreport_adapter.go
- internal/controller/statusreport/statusreport_adapter_test.go
- status/mock_reporter.go
- status/mock_status.go
- status/reporter.go
- status/reporter_github.go
- status/reporter_github_test.go
- status/reporter_gitlab.go
- status/reporter_gitlab_test.go
- status/status.go
- status/status_test.go
* Return the response status code when querying git APIs both for GitLab and GitHub and bubble them up to the controller calls
* Ensure that controllers which run into unrecoverable issues such as 403 codes when reporting to git provider don't  endlessly requeue the reconciliations for the affected resource
> fix(STONEINTG-1252): return status codes in status updates

- cmd/main.go
- config/webhook/manifests.yaml
- internal/controller/snapshot/snapshot_controller_test.go
- internal/webhook/v1beta2/snapshot_webhook.go
- internal/webhook/v1beta2/snapshot_webhook_test.go
- internal/webhook/v1beta2/snapshot_webhook_unit_test.go
- internal/webhook/v1beta2/webhook_suite_test.go
- Add SnapshotCustomValidator to prevent updates to components field
- Components can be set during creation but become immutable afterward
- Other snapshot fields remain updatable
- Include comprehensive test coverage and integration setup
> feat: add validation webhook for snapshot component immutability

- .tekton/integration-service-pull-request.yaml
- .tekton/integration-service-push.yaml
This PR enables ARM64 builds for the integration-service by implementing the matrix build pattern.
- Added `build-platforms` parameter with `linux/x86_64` and `linux/arm64` support
- Converted `build-container` to matrix `build-images` task using `buildah-remote-oci-ta`
- Updated `build-image-index` to collect from `IMAGE_REF[*]` matrix results
- Updated all dependent tasks (deprecated-base-image-check, clair-scan, clamav-scan, rpms-signature-scan) to use `build-image-index` results
- Applied changes to both push and pull-request pipelines
- Uses `buildah-remote-oci-ta` since the original pipeline uses `buildah-oci-ta`
- Matrix builds create separate images for each platform, consolidated by `build-image-index`
- All security scanning tasks now reference the consolidated image index …
> Enable ARM64 builds for integration-service

- cmd/snapshotgc/snapshotgc.go
- cmd/snapshotgc/snapshotgc_test.go
The filterSnapshotsWithKeepSnapshotAnnotation function was initializing its results slice using make([]T, len). This created a slice pre-filled with blank, zero-value snapshot objects before any real snapshots were appended.
When the garbage collector processed this slice, it would immediately try to delete the first blank entry, causing a fatal error because the resource name was an empty string.
This change corrects the slice initialization to use make([]T, 0, cap), which creates a truly empty slice. This ensures that only valid snapshots are processed for deletion. The corresponding unit test has also been updated to assert the slice length.
> fix(stoneintg-1187): Prevent 'resource name empty' error

- .github/CODEOWNERS
> chore: add Nigel to the codeowners config

- integration-tests/pipelines/konflux-e2e-tests.yaml
https://issues.redhat.com/browse/KFLUXDP-345
* use kind clusters for deploying konflux-ci for e2e testing of integration-service
> feat: use kind cluster for e2e testing

- internal/controller/snapshot/snapshot_adapter.go
- internal/controller/snapshot/snapshot_adapter_test.go
- tekton/consts/consts.go
- tekton/integration_pipeline.go
- tekton/integration_pipeline_test.go
* Set the new `konflux-integration-runner` serviceaccount for integration pipelineRuns
> feat(STONEINTG-1215): new serviceaccount for integration pipelineRuns

- integration-tests/pipelines/konflux-e2e-tests.yaml
* pass component-image-repository and component-image-tag to pipelinerun to deploy the built integration-service image in PR to kind cluster and run e2e-tests against 
> fix(STONEINTG-1332): fix e2e-tests integration test pipeline

- tekton/integration_pipeline.go
- tekton/integration_pipeline_test.go
**Problem**
When integration test scenarios use the PipelineRun resource kind (instead of Pipeline), the generateIntegrationPipelineRunFromBase64 function creates pipeline runs by unmarshaling YAML. This can result in incomplete initialization of the pipeline reference structure, leading to nil fields that the WithUpdatedTestsGitResolver method attempted to access without proper validation.
The panic occurred when the code tried to iterate over iplr.Spec.PipelineRef.ResolverRef.Params without checking if:
- PipelineRef was nil
- ResolverRef.Resolver was empty (indicating no resolver configured)
- Params slice was nil or empty
**Solution**
1. Added comprehensive nil and empty checks in WithUpdatedTestsGitResolver:
2. PipelineRef nil check: Return early if iplr.Spec.PipelineRef == nil
3. …
> fix (Stoneintg 1309): fix integration plr can be null 

- config/snapshotgc/snapshotgc.yaml
This PR to fix issue of crashing snapshotgc pods on out of memory crash  
[STONEINTG-1329](https://issues.redhat.com/browse/STONEINTG-1329)
> fix(STONEINTG-1329): increase memory for shanpshotgc

- gitops/snapshot.go
- helpers/scenario.go
- status/reporter_github.go
- status/reporter_github_test.go
Reporting failed optional integration tests as failures to Github is creating noise for users.  Users want to be able to clearly see the difference between a failed required check and a failed optional check so they can determine whether to merge and/or release their changes. Reporting failed optional integration tests using the 'neutral' github status gives users more clarity on how they should proceed given the test results.
> feat(stoneintg-1347): set neutral github check status for optional tests
